### PR TITLE
[Iron] Prepare release 0.22.1

### PR DESCRIPTION
**Pull request by clalancette**
Once this is approved, I'll merge, tag and do the `bloom-release`.

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
@clalancette Can we wait a day or two and do rebase after https://github.com/ros2/rosbag2/pull/1297 will be propagated to the iron?

**Comment by MichaelOrlov** [comment]
@clalancette I've just merged https://github.com/ros2/rosbag2/pull/1330 can we take it in and rebase this PR?

**Comment by clalancette** [comment]
Actually, I'm going to wait a bit longer since I see there are at least 3 other PRs waiting to be backported to Iron.  But we do need to get this in before this Friday (May 19).

**Comment by emersonknapp** [comment]
Trying to push https://github.com/ros2/rosbag2/pull/1337 through and into Iron on emergency priority - but I see that we're holding the other backports for first sync. In the interest of CI time, I created https://github.com/ros2/rosbag2/pull/1338 as a "pre-backport" with the same commit as #1337. Given time constraints I think it's better to do it that way rather than waiting on Rolling test+merge

**Comment by clalancette** [comment]
@emersonknapp @MichaelOrlov I've now rebased this onto the latest iron changes, so this is ready for another review.  Once this is approved I'll go ahead and merge, make a tag, and bloom rosbag2 into iron.

**Review by emersonknapp — APPROVED** [review]

**Review by MichaelOrlov — APPROVED** [review]

**Pull request merged**
