### PR TITLE
Add CLI option to expose bagfile splitting

### PR DESCRIPTION
**Pull request by prajakta-gokhale**
Expose the bagfile splitting functionality in `ros2 bag record`.

Related to https://github.com/ros-security/aws-roadmap/issues/6

### CODE REVIEW

**Comment by Karsten1987** [comment]
@prajakta-gokhale do you want to rebase this to the latest master to have it being able to run CI?

**Comment by Karsten1987** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8660/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4502/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7070/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8580/)

@prajakta-gokhale just fyi, please feel free to tag me/comment on a ticket after a rebase or such. I don't get a notification if you push a commit.

**Comment by prajakta-gokhale** [comment]
We may have to restart the Linux build. It passed when I ran locally.

**Comment by Karsten1987** [comment]
CI again:
Linux: [Build Status](https://ci.ros2.org/job/ci_linux/8662/)

**Pull request merged**
