### PR TITLE
0.15.2

### PR DESCRIPTION
**Pull request by audrow**
Signed-off-by: Audrow Nash <audrow@hey.com>

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
@audrow Out of curiosity. What a rational for new label/release?    
We have only one commit since recently issued 0.15.1.

**Comment by audrow** [comment]
Hi @MichaelOrlov, we're preparing for another rolling release before the Humble branch, so the thinking was to have everything as up-to-date as possible. Although, looking at the last commits, it seems that they're just improving tests, so maybe this isn't necessary.

**Comment by MichaelOrlov** [comment]
@audrow I would propose to wait a bit until some fixes will be made in source code or more tests failure will be addressed.
Currently as far as I am aware at least one more PR was merged addressing tests flakiness on Windows CI build.  
At least make sense to make rebase to the latest master.

**Comment by audrow** [comment]
I'm going to open another PR bumping the minor for Rolling, so that we can make space for Humble.

**Pull request closed without merging**
