### PR TITLE
[humble] Backport. Added support for filtering topics via regular expressions (#1034)-

### PR DESCRIPTION
**Pull request by esteve**
This is a backport of https://github.com/ros2/rosbag2/pull/1034 to Humble

### CODE REVIEW

**Review by jhdcs — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
@esteve I don't mind if you will rename in this PR and in Rolling `--topics-regex` to just simple `-regex` to be compliant with parameters format from rosbag2 recorder.  
We should have caught it during review. Sorry we missed it.

**Review by MichaelOrlov — APPROVED** [review]
@esteve I didn't expect that you will rename `storage_filter.topics_regex` to the simple `storage_filter.regex`.  
As for me it would be more clear if it will be full name `storage_filter.topics_regex`.  
Anyway I approve this MR and it's up to you if you prefer to keep it as.

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/a373802dcda49593a16efb760e2eb61a/raw/303af71374c03d69edfd179d61fece958a357364/ros2.repos
BUILD args:  --packages-above-and-dependencies ros2bag rosbag2_py rosbag2_storage rosbag2_storage_default_plugins rosbag2_transport rosbag2_tests
TEST args:  --packages-above ros2bag rosbag2_py rosbag2_storage rosbag2_storage_default_plugins rosbag2_transport rosbag2_tests
ROS Distro: humble
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10574
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17026/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11586/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17445/)

**Comment by MichaelOrlov** [comment]
It seems Windows build failed due to some infrastructure issue. 
Trying to re-run it.
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17452/)

**Comment by MichaelOrlov** [comment]
@clalancette @audrow It seems something wrong with build infrastructure for Windows build on CI.  
I've ran CI build for Windows a couple times and it failed with some errors seems unrelated to the changes and I can't figure out what exactly wrong.  
Is it known issue with build infrastructure or I've missed somesing?

Could you please help with it?

**Comment by clalancette** [comment]
> Is it known issue with build infrastructure or I've missed something?

The first job you ran failed because of an infrastructure issue on Windows that sometimes fails for reasons we don't understand (though it happens infrequently enough that we just live with it for now).

The second job you ran for reasons I don't understand either.  Other than the above sometimes flaky problem, we don't have any other known Windows infrastructure issues, and Windows CI passed overnight: https://ci.ros2.org/view/nightly/job/nightly_win_rel/2376/

Here's a Humble Windows job *without* these changes to see what happens: * Windows [Build Status](http://ci.ros2.org/job/ci_windows/17458/)

**Comment by MichaelOrlov** [comment]
@clalancette Thanks for helping figuring out what is going on.

Trying to run Windows build one more time:
It seems Windows build failed due to some infrastructure issue. 
Trying to re-run it.
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17461/)

**Comment by esteve** [comment]
> @esteve I didn't expect that you will rename storage_filter.topics_regex to the simple storage_filter.regex.
As for me it would be more clear if it will be full name storage_filter.topics_regex.
Anyway I approve this MR and it's up to you if you prefer to keep it as.

I agree. I've been offline the past few days, so I haven't had time to address your feedback, I can do it on Monday.

**Comment by esteve** [comment]
@MichaelOrlov I've addressed your feedback in #1053 , I'll submit a backport PR for Humble shortly.

**Pull request merged**
