### PR TITLE
Fix --topics flag for ros2 bag play being ignored for all bags after the first one.

### PR DESCRIPTION
**Pull request by hexonxons**
How to reproduce:

We need to have some [splitted](https://github.com/ros2/rosbag2#splitting-recorded-bag-files) log. I can't provide our own log, but I think any log with any messages recorded for 2 topics will be good.

File structure of our log looks like:
```
metadata.yaml      rosbag_12.db3      rosbag_15.db3-shm  rosbag_18.db3-wal  rosbag_21.db3      rosbag_24.db3-shm  rosbag_27.db3-wal  rosbag_30.db3      rosbag_3.db3-shm  rosbag_6.db3-wal
rosbag_0.db3       rosbag_12.db3-shm  rosbag_15.db3-wal  rosbag_19.db3      rosbag_21.db3-shm  rosbag_24.db3-wal  rosbag_28.db3      rosbag_30.db3-shm  rosbag_3.db3-wal  rosbag_7.db3
rosbag_0.db3-shm   rosbag_12.db3-wal  rosbag_16.db3      rosbag_19.db3-shm  rosbag_21.db3-wal  rosbag_25.db3      rosbag_28.db3-shm  rosbag_30.db3-wal  rosbag_4.db3      rosbag_7.db3-shm
rosbag_0.db3-wal   rosbag_13.db3      rosbag_16.db3-shm  rosbag_19.db3-wal  rosbag_22.db3      rosbag_25.db3-shm  rosbag_28.db3-wal  rosbag_31.db3      rosbag_4.db3-shm  rosbag_7.db3-wal
rosbag_10.db3      rosbag_13.db3-shm  rosbag_16.db3-wal  rosbag_1.db3       rosbag_22.db3-shm  rosbag_25.db3-wal  rosbag_29.db3      rosbag_31.db3-shm  rosbag_4.db3-wal  rosbag_8.db3
rosbag_10.db3-shm  rosbag_13.db3-wal  rosbag_17.db3      rosbag_1.db3-shm   rosbag_22.db3-wal  rosbag_26.db3      rosbag_29.db3-shm  rosbag_31.db3-wal  rosbag_5.db3      rosbag_8.db3-shm
rosbag_10.db3-wal  rosbag_14.db3      rosbag_17.db3-shm  rosbag_1.db3-wal   rosbag_23.db3      rosbag_26.db3-shm  rosbag_29.db3-wal  rosbag_32.db3      rosbag_5.db3-shm  rosbag_8.db3-wal
rosbag_11.db3      rosbag_14.db3-shm  rosbag_17.db3-wal  rosbag_20.db3      rosbag_23.db3-shm  rosbag_26.db3-wal  rosbag_2.db3       rosbag_32.db3-shm  rosbag_5.db3-wal  rosbag_9.db3
rosbag_11.db3-shm  rosbag_14.db3-wal  rosbag_18.db3      rosbag_20.db3-shm  rosbag_23.db3-wal  rosbag_27.db3      rosbag_2.db3-shm   rosbag_32.db3-wal  rosbag_6.db3      rosbag_9.db3-shm
rosbag_11.db3-wal  rosbag_15.db3      rosbag_18.db3-shm  rosbag_20.db3-wal  rosbag_24.db3      rosbag_27.db3-shm  rosbag_2.db3-wal   rosbag_3.db3       rosbag_6.db3-shm  rosbag_9.db3-wal
```

For example there are 2 topics recorded: `/topic1` and `/topic2`.
According to code I need to call `ros2 bag play --topics /topic1` to play messages only from `/topic1`. So I've started playing in 1st terminal and start echoing messages in second one, like `ros2 topic echo /topic2`

In 1st terminal I got message something like
```
[INFO] [1611763978.658416823] [rosbag2_storage]: Opened database './rosbag_0.db3' for READ_ONLY.
[INFO] [1611763978.708594529] [rosbag2_storage]: Opened database './rosbag_1.db3' for READ_ONLY.
```

And when messages from `rosbag_1.db3` starts playing I've got messages in 2nd terminal. But in 2nd terminal I was listening for `/topic2` messages!

### CODE REVIEW

**Comment by Karsten1987** [comment]
thanks for the patch. Do you mind filling out the PR description a little bit more with details on how to reproduce this? I'd like to see whether we could come up with a regression test for this.

**Comment by hexonxons** [comment]
@Karsten1987 Done

**Comment by emersonknapp** [comment]
Yeah, this looks good, but I would also like to see a regression test

**Comment by hexonxons** [comment]
@emersonknapp @Karsten1987 regression test is in the branch :)

**Review by emersonknapp — APPROVED** [review]
LGTM - thanks for the patch

**Comment by emersonknapp** [comment]
Gist: https://gist.githubusercontent.com/emersonknapp/c8a36ec75da0a143fa208c2b298e9555/raw/be1708f6da83149c92388f5c3f573c84871a57c2/ros2.repos
BUILD args: --packages-up-to rosbag2_cpp rosbag2_tests
TEST args: --packages-select rosbag2_cpp rosbag2_tests
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/7635
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13654/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8533/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11369/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13718/)

**Comment by hexonxons** [comment]
Could you also release this fix for foxy?

**Comment by emersonknapp** [comment]
If you open up a backport PR (cherry-pick the squashed commit from `master` onto `foxy` branch and open PR against foxy branch - then I'll be happy to review and run CI for that.

**Pull request merged**
