### PR TITLE
Bump iron to 0 22 4

### PR DESCRIPTION
**Pull request by MichaelOrlov**
- Relates https://github.com/ros2/rosbag2/issues/1485

### CODE REVIEW

**Review by clalancette — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
@ros-pull-request-builder retest this please

**Comment by Yadunund** [comment]
Hi @MichaelOrlov I think when this PR was squash merged into `iron`, the `0.22.4` tag was lost and is no longer attached to any commit on the `iron` branch.

image

As a result our [osr_dashboard](https://osrf.github.io/osr_dashboard/?distribution=iron) and tools like `catkin_generate_changelogs` will still pull diffs from `0.22.3`.

If you're okay I can open a PR to bump to `0.22.5` without any changes in the changelog. Once that PR is merged, I will tag the HEAD of `iron` as `0.22.5` and bloom again.

Another option is to delete the `0.22.4` tag,  re-tag the HEAD of `iron` and bloom a new variant of `0.22.4`, ie `0.22.4-2`.

@clalancette any suggestions?

**Comment by MichaelOrlov** [comment]
@Yadunund Sorry about it, my bad.
I've just fixed tag 0.22.4 
image
IMO now releasing iron with 0.22.4-2 doesn't make sense. @clalancette your opinion on that?
I am ok to open a PR to bump to 0.22.5 without any changes in the changelog and then do a bloom release from that.

**Comment by clalancette** [comment]
> IMO now releasing iron with 0.22.4-2 doesn't make sense. @clalancette your opinion on that?

Agreed.

>  I am ok to open a PR to bump to 0.22.5 without any changes in the changelog and then do a bloom release from that.

Yeah, let's go ahead and do this.

**Pull request merged**
