### PR TITLE
Delete obsolete compression_options.cpp from rosbag2_cpp

### LINKED ISSUE #1071: Obsolete "src/rosbag2_cpp/compression_options.cpp"
Since #257, "src/rosbag2_cpp/compression_options.cpp" is removed from "rosbag2_cpp/CMakeLists.txt" (https://github.com/ros2/rosbag2/commit/323f7e9d0799103fb162e4bfec8551470fafd4c5#diff-7b93246f3411ebdf2503d0e0e1fe34363a12fe0c0a4a3d4b24760f7939c78ac6L44) but the file itself is not removed.

### PR DESCRIPTION
**Pull request by MichaelOrlov**
Closes #1071 

`compression_options.cpp` was supposed to be moved to the`rosbag2_compression` package in #257 but was forgotten to delete from `rosbag2_cpp` package. Deleting it now to avoid confusion.

Signed-off-by: Michael Orlov <michael.orlov@apex.ai>

### CODE REVIEW

**Review by emersonknapp — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/201735aaef5920823af8bfa03834ca97/raw/68fc92afd56106dda438b8e3ac5b74902892dc5e/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_cpp rosbag2_tests
TEST args:  --packages-above rosbag2_cpp rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10780
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17265/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11804/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17745/)

**Comment by MichaelOrlov** [comment]
New warning on Windows build is a known issue  and has already been fixed.

**Comment by DLu** [comment]
Should this be backported? I just spent a few minutes searching for the compression options header in humble.

**Comment by emersonknapp** [comment]
@mergifyio backport humble

**Pull request merged**
