### PR TITLE
[Backport/Humble] Notification of significant events during bag recording and playback

### PR DESCRIPTION
**Pull request by gbiggs**
Backports #908 to Humble.

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/6c1703180c5770c61d51d01a7b4f6539/raw/8c7b6492858213d297f35d2374807d7b894effaa/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_cpp rosbag2_interfaces rosbag2_transport rosbag2_tests rosbag2
TEST args:  --packages-above rosbag2_cpp rosbag2_interfaces rosbag2_transport rosbag2_tests rosbag2
ROS Distro: humble
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10474
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16918/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11484/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17317/)

**Review by MichaelOrlov — APPROVED** [review]
@gbiggs Looks good to me.

@audrow This is new feature which we  would like to backport to the Humble.  
I've reviewed it. And I don't see any breaking API or ABI changes. We only adding new API.

**Review by audrow — APPROVED** [review]

**Comment by audrow** [comment]
Looks good to me. Are the PR job failures expected?

**Comment by MichaelOrlov** [comment]
> Looks good to me. Are the PR job failures expected?

Yes. It's known issue https://github.com/ros2/rosbag2/issues/862

**Comment by MichaelOrlov** [comment]
@audrow Can we merge this PR now?

**Comment by audrow** [comment]
Great, one more CI run, just to see if anything has changed - if this is green, I'll merge it:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16980/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11545/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17387/)

**Comment by MichaelOrlov** [comment]
@audrow Can we merge it now?

**Pull request merged**
