### PR TITLE
Merge "Add additional mode of publishing sim time updates (#1036)" to rolling 

### PR DESCRIPTION
**Pull request by kylemarcey**
Original PR #1036 targeted `master` and was overwritten by https://github.com/ros2/rosbag2/commit/fa60ff77b600010023001e373bf95723db71165a

### CODE REVIEW

**Review by MichaelOrlov — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/e277a0e08c5a0042b93b6bdc04e3c130/raw/4fd339c4316f300edd0b3824d5a7e0465a9bd9c3/ros2.repos
BUILD args:  --packages-above-and-dependencies ros2bag rosbag2_py rosbag2_transport rosbag2_tests
TEST args:  --packages-above ros2bag rosbag2_py rosbag2_transport rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10586
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17038/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11598/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17463/)

**Comment by MichaelOrlov** [comment]
`test_burst__rmw_fastrtps_dynamic_cpp` failed with error
```
2022-07-28T02:21:11.9855933Z 59: /__w/rosbag2/rosbag2/ros_ws/src/42oufxecqtv/rosbag2/rosbag2_transport/test/rosbag2_transport/test_burst.cpp:366: Failure
2022-07-28T02:21:11.9856025Z 59: Value of: replayed_topic2
2022-07-28T02:21:11.9856123Z 59: Expected: size is equal to 3
2022-07-28T02:21:11.9856410Z 59:   Actual: { 16-byte object <10-55 E7-74 E1-55 00-00 00-55 E7-74 E1-55 00-00> }, whose size 1 doesn't match
2022-07-28T02:21:11.9856643Z 59: Failed to delete participant[  FAILED  ] RosBag2PlayTestFixture.burst_bursting_only_filtered_topics (10038 ms)
2022-07-28T02:21:11.9856875Z 59: [----------] 7 tests from RosBag2PlayTestFixture (11548 ms total)
2022-07-28T02:21:11.9859309Z 59: 
2022-07-28T02:21:11.9859519Z 59: [----------] Global test environment tear-down
2022-07-28T02:21:11.9859650Z 59: [==========] 7 tests from 1 test suite ran. (11548 ms total)
2022-07-28T02:21:11.9859734Z 59: [  PASSED  ] 6 tests.
2022-07-28T02:21:11.9859833Z 59: [  FAILED  ] 1 test, listed below:
2022-07-28T02:21:11.9860003Z 59: [  FAILED  ] RosBag2PlayTestFixture.burst_bursting_only_filtered_topics
2022-07-28T02:21:11.9860141Z 59: 
2022-07-28T02:21:11.9860219Z 59:  1 FAILED TEST
2022-07-28T02:21:11.9860364Z 59: -- run_test.py: return code 1
2022-07-28T02:21:11.9860823Z 59: -- run_test.py: inject classname prefix into gtest result file '/__w/rosbag2/rosbag2/ros_ws/build/rosbag2_transport/test_results/rosbag2_transport/test_burst__rmw_fastrtps_dynamic_cpp.gtest.xml'
2022-07-28T02:21:11.9861236Z 59: -- run_test.py: verify result file '/__w/rosbag2/rosbag2/ros_ws/build/rosbag2_transport/test_results/rosbag2_transport/test_burst__rmw_fastrtps_dynamic_cpp.gtest.xml'
2022-07-28T02:21:11.9861412Z 59/78 Test #59: test_burst__rmw_fastrtps_dynamic_cpp ...................................***Failed   11.79 sec
2022-07-28T02:21:11.9861477Z test 60
2022-07-28T02:21:11.9861598Z       Start 60: test_qos__rmw_fastrtps_dynamic_cpp
```

**Comment by MichaelOrlov** [comment]
It seems CI failures unrelated to the changes from this PR.
Trying to re-run failing CI jobs.

* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17467/)

**Comment by kylemarcey** [comment]
@MichaelOrlov I tried to reproduce the `test_burst__rmw_fastrtps_dynamic_cpp` failure locally, but was not able to. Maybe it is a flaky test?

**Comment by MichaelOrlov** [comment]
CI passed after second iteration.
Merging then

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-8-18-2022/27050/1

**Pull request merged**
