### PR TITLE
[humble] Fix typo to properly restore SIGINT handler

### LINKED ISSUE #1686: [rosbag2_py] Typo in Recorder's signal restoration? (second `SIGTERM` should be `SIGINT`)
## Description
Per comment in
https://github.com/ros2/rosbag2/issues/1678#issuecomment-2143936223
Line 239 should be `SIGINT`, not `SIGTERM`:
https://github.com/ros2/rosbag2/blob/8c94497f4a13464538457d81433d85fa13c760a9/rosbag2_py/src/rosbag2_py/_transport.cpp#L234-L240

fyi @MichaelOrlov 

### Expected Behavior
Line 239 should be `SIGINT`, not `SIGTERM`

### Actual Behavior
It is `SIGTERM`

## To Reproduce
See code.

## System (please complete the following information)
 - OS: Any
 - ROS 2 Distro: Humble
 - Install Method: Any
 - Version: humble

## Additional context
Relates #1678

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
- Closes #1686

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
It appears that this typo is also present in `iron`, so I can retarget this PR + request backport, or we can forward port.
Please let me know which.

**Review by MichaelOrlov — APPROVED** [review]
LGTM

**Review by fujitatomoya — APPROVED** [review]
good eye 👁️ lgtm with green CI

**Review by MichaelOrlov — CHANGES_REQUESTED** [review]
@EricCousineau-TRI While changes in this PR will certainly fix a typo and will properly return the original signal handler for `SIGINT`, but it will not solve a problem reported in the https://github.com/ros2/rosbag2/issues/1686.

Among properly returning original signal handlers need yet memorize the deferred signal in the static member variable and call the original `SIGINT` handler on exit. See https://github.com/ros2/rosbag2/pull/1685/files#diff-c85fd024e7d68c762d60d25e2ba155bcc527f04c937ed09adc893ea241fdc61cR241-R254 for reference.

Also, I would encourage you to cherry-pick my newly added `test_process_sigint_in_recorder(tmp_path, storage_id, capfd):` unit test from the #1685 
https://github.com/ros2/rosbag2/pull/1685/files#diff-f990d34f689d7cde53ab226e2b1b96b5573c4e050ccf698cc182e76bd72fc0eeR88-R129
tio make sure tha the original Python SIGINT handler called.

**Review by MichaelOrlov — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
Pulls: ros2/rosbag2#1687
Gist: https://gist.githubusercontent.com/MichaelOrlov/1b19779b38d132c8d347c6a3d4655481/raw/dc63ceb2b44ab11cb2cab457a6df42d697ad22dc/ros2.repos
BUILD args:  --packages-above-and-dependencies ros2bag rosbag2_py
TEST args:  --packages-above ros2bag rosbag2_py
ROS Distro: humble
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14041
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21231/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15546/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/705/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21953/)

**Pull request merged**
