### PR TITLE
Add CPU usage to rosbag2_performance_benchmarking results report

### PR DESCRIPTION
**Pull request by MichaelOrlov**
- Add average CPU usage for producer and recorder to rosbag2_performance_benchmarking results report
- Add per core CPU usage to rosbag2_performance_benchmarking results report

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
@carlossvg Could you please review this PR?

**Comment by hwoithe** [comment]
This pull request includes an import to `psutil` in the `benchmark_launch.py` file.
https://github.com/ros2/rosbag2/pull/1304/commits/b180d8d22289f72d8f6c4679324d627f90512d87#diff-dbce924e9cad0a9fd6bcf28650df050ec6b5753274bee26bc86b9105f32193cdR54

I am wondering if we should add `python3-psutil` as a package dependency.

For example, ros2doctor includes `python3-psutil` in its `package.xml` file.
https://github.com/ros2/ros2cli/blob/1e7df98d9e5677f554869fb349b552bbc96235ec/ros2doctor/package.xml#L20

**Comment by clalancette** [comment]
> I am wondering if we should add `python3-psutil` as a package dependency.

Yes, it definitely should.  Thanks for pointing it out.

**Comment by MichaelOrlov** [comment]
@hwoithe I added missing python lib dependencies in new commit https://github.com/ros2/rosbag2/pull/1304/commits/95648466974cddc24ae76253e2ad103d39e72de7

**Review by emersonknapp — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/a4e59f3d3273aa01f7c1079485bd061f/raw/4dc123a7978c1392cff761ee64e62457680b77c8/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_performance_benchmarking
TEST args:  --packages-above rosbag2_performance_benchmarking
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12129
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18817/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13350/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19563/)

**Pull request merged**
