### PR TITLE
[Iron] Resolve recording option problem

### PR DESCRIPTION
**Pull request by Barry-Xu-2018**
Address #1620

### CODE REVIEW

**Review by MichaelOrlov — APPROVED** [review]
LGTM with green CI.

**Review by fujitatomoya — APPROVED** [review]
lgtm, starting CI.

**Comment by fujitatomoya** [comment]
https://github.com/ros2/rosbag2/actions/runs/9028077952/job/24807954745?pr=1649 workflow failing, is this unrelated?

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21054/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15357/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21751/)

**Comment by MichaelOrlov** [comment]
> https://github.com/ros2/rosbag2/actions/runs/9028077952/job/24807954745?pr=1649 workflow failing, is this unrelated?

Yes, the failure is unrelated. It fails with the error message:
```
     entrypoint = find_launch_test_entrypoint(path)
2024-05-10T06:52:42.1128396Z ../../../../build/launch_testing/launch_testing/pytest/hooks.py:178: in find_launch_test_entrypoint
2024-05-10T06:52:42.1129001Z     module = import_path(path, root=None)
2024-05-10T06:52:42.1129695Z E   TypeError: import_path() missing 1 required keyword-only argument: 'consider_namespace_packages'
2024-05-10T06:52:42.1130514Z --- generated xml file: /__w/rosbag2/rosbag2/ros_ws/build/ros2bag/pytest.xml ---
2024-05-10T06:52:42.1131081Z =========================== short test summary info ============================
2024-05-10T06:52:42.1131855Z ERROR test - TypeError: import_path() missing 1 required keyword-only argument: 'consider_namespace_packages'
2024-05-10T06:52:42.1132592Z !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
```
The failure described in the https://github.com/ros2/launch/issues/765 and as far as I understand was fixed on Rolling in the https://github.com/ros2/launch/pull/766. But was not backported to the Iron and Humble. 

I've pinged @clalancette about it in the https://github.com/ros2/launch/pull/766#issuecomment-2095290591 but still no response.  
@clalancette A friendly ping here again about Iron and Humble `build_and_test` Ci jobs failure.

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport humble

**Pull request merged**
