### PR TITLE
0.15.12

### PR DESCRIPTION
**Pull request by audrow**
Bumps Humble from 0.15.11 to 0.15.12.

### CODE REVIEW

**Review by MichaelOrlov — COMMENTED** [review]
@audrow can you please rebase. I've not seen your PR and just merged mine.

**Comment by MichaelOrlov** [comment]
@audrow we are missing https://github.com/ros2/rosbag2/pull/1722

BTW, with those PR I also fixed some warnings on RHEL build.

**Comment by audrow** [comment]
> @audrow we are missing #1722
> 
> BTW, with those PR I also fixed some warnings on RHEL build.

I rebased and regenerated the change logs 👍  Glad to hear it fixes some of the RHEL warnings.

**Review by MichaelOrlov — APPROVED** [review]
LGTM.

**Pull request merged**
