### PR TITLE
Feature/start stop time

### PR DESCRIPTION
**Pull request by Kaju-Bubanja**
Fixes [#618](https://github.com/ros2/rosbag2/issues/618). This feature is not tested and not in a state to be merged. But I still put it out here, in case anybody else wants this hack. It works well for me so maybe others find it useful. I also do not plan to getting it into a mergable state. If somebody else feels like polishing it feel free or if this is inappropriate to have here just close the PR.

### CODE REVIEW

**Comment by Karsten1987** [comment]
please target `master` and not `foxy` as your base branch for this PR.

**Comment by Kaju-Bubanja** [comment]
Any reason for that? Isn't master behind foxy? I just see a way bigger diff to master, I also based it of off foxy. I think somebody seeing this huge div is going to be discouraged to use the feature, compared to the small diff to foxy.

**Comment by emersonknapp** [comment]
> Any reason for that? Isn't master behind foxy?

`master` is the latest development branch, and is about 7 months of development ahead of the distro release branch `foxy`, which has only received backported bugfixes since the Foxy release in June 2020.

The practice is for new development to happen on the master branch, and for fixes or non-API-breaking new features to then be selectively backported to released ROS distributions.

**Comment by Kaju-Bubanja** [comment]
Ah, makes sense. Is that true for all ros packages? Because I'm quite sure I saw some where master was pointing to ros1 and foxy was way ahead of master. There also might have been a ros2 branch, I'm not completely sure anymore. Is it possible that master is always latest, except if there is a ros2 branch? Than master is latest ros1 dev and ros2 is latest ros2 dev?

**Comment by emersonknapp** [comment]
> Ah, makes sense. Is that true for all ros packages? Because I'm quite sure I saw some where master was pointing to ros1 and foxy was way ahead of master. There also might have been a ros2 branch, I'm not completely sure anymore. Is it possible that master is always latest, except if there is a ros2 branch? Than master is latest ros1 dev and ros2 is latest ros2 dev?

It's generally true for most packages - there are always exceptions. In the case of packages that support both ros1 and ros2, `master` was originally for ROS1, so the `ros2` branch tracks latest developments for ROS2 - while branches named after specific distributions are release branches. Sometimes that naming looks like `DISTRO-devel`, e.g. `kinetic-devel`, instead of just `kinetic`.

**Comment by Kaju-Bubanja** [comment]
Is there a way to speed up the seeking to the right message? Because right now it takes quite some time for the reader to go to the start position, because it has to read each message. But I saw no other method which I could use to skip ahead or just skip reading the messages.

**Comment by emersonknapp** [comment]
You'll also want to rebase your changes on master so that we can review the feature rather than all the differences between this branch and foxy :)

As for speeding up seeking - the SQLite database allows for random access. But what I think I'd like to see is a targeted API proposal (without implementation!) for the Player to expose the desired behavior.

**Comment by Kaju-Bubanja** [comment]
Already looks like the rebase worked. Cool feature of git

**Comment by Kaju-Bubanja** [comment]
Hmmm unfortunately looks like the rebase broke this feature, since I can't built rosbag2_storage in master as described here: https://github.com/ros2/rosbag2/issues/650. Isn't master always at least buildable?

**Comment by emersonknapp** [comment]
> Isn't master always at least buildable?

Yes - the master branch builds. You can see that on https://github.com/ros2/rosbag2/actions?query=event:schedule (plus or minus an occasional flaky test failure) and https://ci.ros2.org/view/nightly/job/nightly_linux_release/ (which builds and tests all of https://github.com/ros2/ros2/blob/master/ros2.repos

Even the check on this PR built https://github.com/ros2/rosbag2/pull/622/checks?check_run_id=1885762308 (the tests failed though - it's at least the linters as a start). This suggests that something is incorrect in your local setup.

**Comment by emersonknapp** [comment]
Closing - this feature has been implemented

**Comment by kosuke55** [comment]
With which PR was this feature implemented?

**Comment by Kaju-Bubanja** [comment]
https://github.com/ros2/rosbag2/issues/696

**Comment by emersonknapp** [comment]
More specifically as the work on https://github.com/ros2/rosbag2/issues/55 - there was a string of PRs involved to build the infrastructure, but pause/resume was enabled in https://github.com/ros2/rosbag2/pull/704

**Pull request closed without merging**
