### PR TITLE
Revert "[Compression - 3] Add compressor interface"

### PR DESCRIPTION
**Pull request by piraka9011**
Reverts ros2/rosbag2#218 because it wasn't squashed.

Signed-off-by: Anas Abou Allaban allabana@amazon.com

### CODE REVIEW

**Comment by thomas-moulard** [comment]
I'll leave @Karsten1987 judge what needs to be done there, but we accidentally pushed 9 commits, then with it we go to 9 + 1 (revert) + 1 (new squashed commit) = 11 commits. Maybe we can just let it go for this time?

**Comment by Karsten1987** [comment]
The same behavior happened already for #216 and #217 as both PRs previously weren't squashed. So in fact you've pushed 17 commits instead of only three needed if squashing, afaict. I am okay with it as it's mainly tackling your `rosbag2_compression` package. Which means you might want to clean up the changelog correctly when releasing. 
I would appreciate though to squash and merge future PRs.

**Comment by piraka9011** [comment]
>  I would appreciate though to squash and merge future PRs.

Will do, thanks for your input!

**Comment by thomas-moulard** [comment]
@Karsten1987 Is there any reason not to squash in this repo? You may want to just completely [disable other merge options in the repo settings directly](https://help.github.com/en/github/administering-a-repository/configuring-commit-squashing-for-pull-requests).

**Comment by Karsten1987** [comment]
@thomas-moulard you should be able to re-write the history for this PR and manually squash commits into its top-level PRs.

**Pull request closed without merging**
