### PR TITLE
Revert PR #330 "Add QoS profiles field to metadata struct"

### PR DESCRIPTION
**Pull request by emersonknapp**
This reverts https://github.com/ros2/rosbag2/pull/330 due to broken windows build

Signed-off-by: Emerson Knapp <emerson.b.knapp@gmail.com>

### CODE REVIEW

**Comment by emersonknapp** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9799/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5420/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7964/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9659/)

**Comment by emersonknapp** [comment]
Failed to vcs import urdf... seems confusing. Retrying

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9800/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5421/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7965/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9660/)

**Comment by jacobperron** [comment]
@emersonknapp I think it's a typo in the repos file

**Comment by jacobperron** [comment]
```diff
- url: https`://github.com/ros2/urdf.git
+ url: https://github.com/ros2/urdf.git
```

**Comment by emersonknapp** [comment]
Yeah, don't know where that came from 
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9801/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5422/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7966/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9661/)

**Comment by Karsten1987** [comment]
I understand that reverting would resolve the broken windows CI, but wouldn't it make sense to actually address the issue directly here? I mean, we have to run CI anyway.

**Comment by emersonknapp** [comment]
> I mean, we have to run CI anyway.

I guess you're right, but it's really unfortunate that this is true. It should be easy to revert breaking changes.

**Comment by jacobperron** [comment]
If this gets resolved, then I can continue with with https://github.com/ros2/launch/pull/346 :wink:

**Comment by emersonknapp** [comment]
This CI run is almost done, when the windows build passes, let's merge the revert. I'd rather be trigger happy on reverts than on new changes.

**Comment by emersonknapp** [comment]
Green, merging. I'll reopen the PR and run CI ;) my bad, everyone

**Pull request merged**
