### PR TITLE
Switch to target_link_libraries everywhere.

### PR DESCRIPTION
**Pull request by clalancette**
There is no need to use ament_target_dependencies.

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19887/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14373/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20596/)

**Review by fujitatomoya — COMMENTED** [review]
lgtm

(not related to this PR) https://github.com/ros2/rosbag2/pull/1504/files#diff-81a326226779dbc5abab3808861f8664841bdafaed9ff22ebf59ae30b6233219L281 should be `test_msgs_TARGETS`, there is a typo. can you also fix that too?

**Comment by clalancette** [comment]
> (not related to this PR) https://github.com/ros2/rosbag2/pull/1504/files#diff-81a326226779dbc5abab3808861f8664841bdafaed9ff22ebf59ae30b6233219L281 should be `test_msgs_TARGETS`, there is a typo. can you also fix that too?

@fujitatomoya Can you paste a new link?  For whatever reason, the one above isn't showing me anything other than the lines from this PR.

**Comment by fujitatomoya** [comment]
@clalancette this one, https://github.com/ros2/rosbag2/blob/9855072566f8fb46a2bdd20cc217d1a0c2b03e82/rosbag2_transport/CMakeLists.txt#L281 i guess it is typo.

**Comment by clalancette** [comment]
> i guess it is typo.

Actually, it turns out that that test doesn't depend on test_msgs at all, so I removed the typo along with a couple of other unused dependencies.

**Comment by clalancette** [comment]
New CI with the latest changes:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19891/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14375/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20598/)

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI

**Review by MichaelOrlov — APPROVED** [review]
LGTM

**Comment by MichaelOrlov** [comment]
@ros-pull-request-builder retest this please

**Comment by clalancette** [comment]
Given that the CI was green, I'm going to go ahead and merge this one.

**Comment by MichaelOrlov** [comment]
@clalancette It is ok to merge since the last time rpr job failed with a known issue in the services.

**Pull request merged**
