### PR TITLE
Added support for excluding topics via regular expressions

### PR DESCRIPTION
**Pull request by esteve**
This PR adds `--exclude` (and `-x`) as an option to `ros2 bag play` to exclude topics from being replayed.

### CODE REVIEW

**Comment by esteve** [comment]
@jhdcs thanks for the prompt review. One thing that differs from `ros2 bag record --exclude` is that this PR accepts multiple regular expressions. Would it be better to keep it consistent and only accept one? It's the same case as with `ros2 bag play --regex`

**Comment by jhdcs** [comment]
I feel like keeping it consistent would be best, at least for the moment. If in future we decide that we need to have multiple regular expression support, we can open a new issue at that time and change everything over.

**Comment by esteve** [comment]
@jhdcs I've updated this PR so that `ros2 bag play --exclude` only takes one regex, so that it matches the behavior of `ros2 bag record --exclude`

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/4ddd09a6f289164fd88305e18d2c6c78/raw/06ed49f0a9fbb6fc94981ef7e363abac755edc6f/ros2.repos
BUILD args:  --packages-above-and-dependencies ros2bag rosbag2_py rosbag2_storage rosbag2_storage_default_plugins rosbag2_transport rosbag2_tests
TEST args:  --packages-above ros2bag rosbag2_py rosbag2_storage rosbag2_storage_default_plugins rosbag2_transport rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10634
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17103/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11652/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17520/)

**Comment by esteve** [comment]
@jhdcs @MichaelOrlov the CI issues don't seem to be related to the changes in this PR, but I could be wrong. Did they happen in previous PRs?

**Comment by MichaelOrlov** [comment]
@esteve Yes  this  is known issue and unrelated to the changes from this PR.  
I am sorry I was on vacation and forgot to merge this PR.

**Pull request merged**
