### PR TITLE
Add API samples for Python

### PR DESCRIPTION
**Pull request by DLu**
In lieu of @gbiggs fixing #887, I cherry-picked the commit here and then renamed things based on @MichaelOrlov 's [comment](https://github.com/ros2/rosbag2/pull/887#issuecomment-1242609044)

### CODE REVIEW

**Review by MichaelOrlov — CHANGES_REQUESTED** [review]
@DLu Thank you for moving forward with this PR.
Could you please fix linter errors
```
Error Message
AssertionError: Found 3 code style errors / warnings:
  ./rosbag2_examples_py/data_generator_node.py:8:1: E302 expected 2 blank lines, found 1
  ./rosbag2_examples_py/data_generator_executable.py:34:1: E305 expected 2 blank lines after class or function definition, found 1
  ./rosbag2_examples_py/simple_bag_recorder.py:8:1: E302 expected 2 blank lines, found 1
assert 1 == 0
```
And add copyright to the python files with the same template as in https://github.com/ros2/rosbag2/blob/6160bb35a31593b324bdcd67e3f44d7dbf24e23c/rosbag2_examples/rosbag2_examples_cpp/src/simple_bag_recorder.cpp#L1-L13

**Comment by MichaelOrlov** [comment]
@ros-pull-request-builder retest this please

**Review by MichaelOrlov — APPROVED** [review]
@DLu Thanks for PR.
LGTM.

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/758e2c906fcfb97e3e7be59b516d99cc/raw/fe8d10c5fe162ccc871b2f1694188c8e7e2b8846/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_examples_py
TEST args:  --packages-above rosbag2_examples_py
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/11619
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18243/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12776/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18917/)

**Comment by MichaelOrlov** [comment]
@DLu Can you please rebase your branch on top of latest `rolling`?
CI fails due to absent fixes from https://github.com/ros2/rosbag2/pull/1257

**Comment by DLu** [comment]
@MichaelOrlov Ready to go!

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/758e2c906fcfb97e3e7be59b516d99cc/raw/fe8d10c5fe162ccc871b2f1694188c8e7e2b8846/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_examples_py
TEST args:  --packages-above rosbag2_examples_py
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/11645
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18280/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12808/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18948/)

**Comment by MichaelOrlov** [comment]
@DLu CI has warnings. Could you please address them?
```
Error Message
AssertionError: Found 5 code style errors / warnings:
  ./rosbag2_examples_py/data_generator_node.py:17:1: I100 Import statements are in the wrong order. 'from example_interfaces.msg import Int32' should be before 'from rclpy.serialization import serialize_message'
  ./rosbag2_examples_py/data_generator_node.py:23:1: CNL100 Class definition does not have a new line.
  ./rosbag2_examples_py/simple_bag_recorder.py:19:1: I100 Import statements are in the wrong order. 'import rosbag2_py' should be before 'from std_msgs.msg import String'
  ./rosbag2_examples_py/simple_bag_recorder.py:23:1: CNL100 Class definition does not have a new line.
  ./rosbag2_examples_py/data_generator_executable.py:17:1: I100 Import statements are in the wrong order. 'from example_interfaces.msg import Int32' should be before 'from rclpy.serialization import serialize_message'
assert 1 == 0
```

**Comment by DLu** [comment]
Two things: 
 1) I'm not familiar with this new style of CI. Why isn't this a github hook?
 2) Is there a specific invocation I can use to generate the code style warnings above? They didn't show up with pytest and there's no pre-commit settings.

**Comment by clalancette** [comment]
> 1. I'm not familiar with this new style of CI. Why isn't this a github hook?

Just to be clear, this isn't new at all.  This has been the CI practice for ROS 2 for approximately 7 years.  There are definitely arguments to be made that this should be a GitHub hook, but doing it this way means that OSRF is ultimately in control of running CI.  Regardless, this isn't the place to debate this.

> * Is there a specific invocation I can use to generate the code style warnings above? They didn't show up with pytest and there's no pre-commit settings.

If you follow the instructions on http://docs.ros.org/en/rolling/Installation/Alternatives/Ubuntu-Development-Setup.html on installing dependencies, it will install all of the pytest/flake8 hooks you need.

**Comment by DLu** [comment]
I apologize if my question about the Github hook came off as combative, but I just didn't understand what was going on. Is there documentation about this kind of CI? Also, not to be pedantic, but do you still work for OSRF?

**Comment by MichaelOrlov** [comment]
@clalancette I am also curious how to reproduce or catch errors from `ament_flake8` locally.
I have tried to run `colcon test --packages-select rosbag2_examples_py` there are no errors.
Also have tried to run the same command as on CI 
```
colcon test --base-paths "src" --build-base "build" --install-base "install" --event-handlers console_direct+ --executor sequential --retest-until-pass 2 --ctest-args -LE xfail --pytest-args -m "not xfail" --packages-above rosbag2_examples_py
```
Still no errors was reported. I've double checked I have up to date version of the `ament_flake8` in my local environment.
Why on CI it is reporting errors/warnings while on local run not?

**Comment by MichaelOrlov** [comment]
Trying to re-run CI one more time
Gist: https://gist.githubusercontent.com/MichaelOrlov/758e2c906fcfb97e3e7be59b516d99cc/raw/fe8d10c5fe162ccc871b2f1694188c8e7e2b8846/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_examples_py
TEST args:  --packages-above rosbag2_examples_py
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/11729
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18380/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12921/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19052/)

@ros-pull-request-builder retest this please

**Comment by MichaelOrlov** [comment]
@clalancette I've spent some time trying to investigate situation why CI job giving us warning errors and we can't reproduce it locally.
The reasoning for that seems in github synchronization issue. It turns out that I started CI jobs right after @DLu made fixes in [more linting](https://github.com/ros2/rosbag2/pull/1253/commits/e500cfa42a87a9511244c1f8136846bb26463d46) commit and let me know about it.
From CI logs I see that `colcon test` picked up old version without latest changes in [more linting](https://github.com/ros2/rosbag2/pull/1253/commits/e500cfa42a87a9511244c1f8136846bb26463d46) commit. 
I have tried to rerun CI - and now it passes green.

@DLu Sorry for confusion with false CI warnings. It was surprise for me as well.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-4-20-2023/31087/1

**Pull request merged**
