### PR TITLE
Add workflow to run colcon build and colcon test

### PR DESCRIPTION
**Pull request by thomas-moulard**

### CODE REVIEW

**Comment by thomas-moulard** [comment]
@Karsten1987 I'll double check tomorrow, but it seems this is working!

**Comment by Karsten1987** [comment]
@thomas-moulard there seems to be quite some errors in the testing phase.
From what I can see, they are unrelated to the actual rosbag tests, but given that there are failures occurring, but the overall action returns as `successful` I am wondering if tests failures would be reported correctly. 
Do you have an example where the same code runs with a warning/error on test failures?

**Comment by thomas-moulard** [comment]
We got CI failures in the past for sure, most likely what you're interpreting as an error is related to code coverage I believe (and hence is expected).

I opened a draft PR to demonstrate a failling build, it's this commit + another one breaking the build on purpose: https://github.com/ros2/rosbag2/pull/231

**Comment by zmichaels11** [comment]
Rebased onto master and re-running GH Actions

**Pull request merged**
