### PR TITLE
[foxy] Enable sanitizers only if code actually can run (#572)

### PR DESCRIPTION
**Pull request by jacobperron**
Backport #572 to Foxy.

### CODE REVIEW

**Comment by gbiggs** [comment]
CI:

- Linux [Build Status](https://ci.ros2.org/job/ci_linux/)
- Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/)
- Windows [Build Status](https://ci.ros2.org/job/ci_windows/)

**Review by gbiggs — APPROVED** [review]

**Comment by jacobperron** [comment]
I've retriggered windows CI: [Build Status](https://ci.ros2.org/job/ci_windows/16374/)

Using build flags `--packages-above-and-dependencies rosbag2_cpp` and test flags `--packages-above rosbag2_cpp`, which should make the CI duration a bit shorter.

**Comment by jacobperron** [comment]
The Windows test failure and cmake warnings appear unrelated.

**Comment by gbiggs** [comment]
It should be good to go in, then.

**Review by emersonknapp — APPROVED** [review]

**Pull request merged**
