### PR TITLE
[foxy backport] Zstd should not install internal headers - some of them try include others that aren't installed. We don't use them. Avoid the situation (#631)

### PR DESCRIPTION
**Pull request by emersonknapp**
Backport #631 to Foxy

### CODE REVIEW

**Review by Karsten1987 — APPROVED** [review]
lgtm given the PR build runs through.
I think technically that's already a breaking change (people might link against the installed headers), but I feel confident to let that slip here.

**Comment by emersonknapp** [comment]
> I think technically that's already a breaking change (people might link against the installed headers)

Yes, I think you're right, but I also feel confident that nobody knows about or uses these headers.

**Comment by emersonknapp** [comment]
@ros-pull-request-builder retest this please

**Comment by emersonknapp** [comment]
The failure is just the API/ABI checker failing on these Zstd headers - I'll merge this and get a Foxy patch build out for rosbag2 in hopes that we can remedy the situation

**Pull request merged**
