### PR TITLE
Revert "Add the ability to record any key/value pair in the 'custom' …

### PR DESCRIPTION
**Pull request by Blast545**
…field in metadata.yaml (#976)"

Just checking if the current errors in the buildfarm come from that PR.
https://ci.ros2.org/view/nightly/job/nightly_win_rel/2257/testReport/junit/rosbag2_compression/SequentialCompressionWriterTest/open_throws_on_bad_compression_format/

This reverts commit e156eb9e38c377df33e5075ab7fa48f3b52eaa12.

### CODE REVIEW

**Comment by Blast545** [comment]
Reproducing the failure: 

[Build Status](https://ci.ros2.org/job/ci_windows/16862/)

**Comment by MichaelOrlov** [comment]
@Blast545 I've tried to run tests for the `rosbag2_compression` package with #976 on my local machine and they are passing without any errors.

**Comment by Blast545** [comment]
@MichaelOrlov Thanks for taking a look! Sometimes the test regressions only happen on the buildfarm, I'm just checking to make sure it's not related to other changes happening on the stack.

**Comment by MichaelOrlov** [comment]
cc: @t0ny-peng

**Comment by Blast545** [comment]
FYI: @clalancette

**Comment by clalancette** [comment]
@t0ny-peng @MichaelOrlov Given that this PR is clearly the cause of the regressions we are seeing, and that today is the API and feature freeze, I'm thinking that we should go ahead with this PR and revert this.  Thoughts?

**Comment by t0ny-peng** [comment]
@clalancette Please revert it as discussed if it's causing trouble. Sorry I don't have Windows machine to debug this flaky test.

**Comment by clalancette** [comment]
All right, here is full CI on this revert PR to check:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16518/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11105/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16889/)

**Comment by clalancette** [comment]
@Blast545 Can you please sign-off on the revert commit to make the DCO bot happy?

**Comment by Blast545** [comment]
@clalancette Yes! Just forced push the signoff and marked the PR ready for review.

**Comment by clalancette** [comment]
I'm going to go ahead and merge this one for now.  We can reinstate it onto Rolling (in two weeks time) once the CI failures have been investigated.

**Review by clalancette — APPROVED** [review]

**Pull request merged**
