### PR TITLE
Backport. Add use_sim_time option to record verb

### PR DESCRIPTION
**Pull request by KeisukeShima**
This is backport of the #994 and #1014 to the Humble branch
Addressing issue #764

### CODE REVIEW

**Comment by KeisukeShima** [comment]
@audrow I could not add you as a reviewer because I do not have permission in this repository.
Could you review this PR?

**Comment by audrow** [comment]
Hey, I've added this to the Humble patch board, since we've got the release candidate now. We can merge this after the Humble release date, May 23rd.

**Review by audrow — COMMENTED** [review]
Hey, I've added this to the Humble patch board, since we've got the release candidate now. We can merge this after the Humble release date, May 23rd.

**Comment by wep21** [comment]
@audrow friendly ping

**Comment by audrow** [comment]
It's probably good, I'll just run CI before merging.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17017/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11578/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17435/)

**Review by audrow — APPROVED** [review]
Looks good to me!

**Comment by audrow** [comment]
@ros-pull-request-builder retest this please

**Pull request merged**
