### PR TITLE
Add in a missing cstdint include.

### LINKED ISSUE #1320: Missing cstdint include
Fails to build on GCC 13.1.1 due to a missing cstdint include in the following file

https://github.com/ros2/rosbag2/blob/3fd28f09cb69700a31dfafa4351c80cc452274c9/rosbag2_compression/include/rosbag2_compression/compression_options.hpp#L29

### PR DESCRIPTION
**Pull request by clalancette**
This should fix #1320

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18672/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13199/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19400/)

**Review by mjcarroll — APPROVED** [review]

**Review by MichaelOrlov — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport iron

**Comment by tastyherring** [comment]
https://github.com/Mergifyio backport humble

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport humble

**Pull request merged**
