### PR TITLE
[foxy backport] export shared_queues_vendor (#434)

### PR DESCRIPTION
**Pull request by Karsten1987**
backports https://github.com/ros2/rosbag2/pull/434

### CODE REVIEW

**Comment by Karsten1987** [comment]
@ros-pull-request-builder retest this please.

**Comment by Karsten1987** [comment]
@ros-pull-request-builder retest this please.

**Comment by Karsten1987** [comment]
ping @emersonknapp @zmichaels11

**Comment by emersonknapp** [comment]
The failures should not be present if you rebase on foxy, after merging the testing change. (not sure about DCO though)

**Pull request merged**
