### PR TITLE
Add python binding to close the SequentialWriter

### LINKED ISSUE #127: ros2: recording doesn't create metadata.yaml
`rqt_bag` recordings leave the bag without `metadata.yaml` file, which makes it unusable by some tooling and requires a `ros2 bag reindex`

### PR DESCRIPTION
**Pull request by Yadunund**
Required to fix https://github.com/ros-visualization/rqt_bag/issues/127

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
@ros-pull-request-builder retest this please

**Review by MichaelOrlov — APPROVED** [review]
LGTM

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/58901fb4df9691add3c91d1a433def9d/raw/6e1f8accecd041b5e6286d37ac871f7eb711a651/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_py
TEST args:  --packages-above rosbag2_py
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12082
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18763/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13287/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19505/)

**Comment by emersonknapp** [comment]
@mergifyio backport iron

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2023-05-18/31587/1

**Pull request merged**
