### PR TITLE
[Humble] move storage preset validation to sqlite3 plugin (backport #1135)

### PR DESCRIPTION
**Pull request by wep21**
Currently, it is impossible to record bag with mcap storage plugin by the follwing error at humble.
```
❯ ros2 bag record -a -s mcap
[INFO] [1669557755.363458962] [rosbag2_recorder]: Press SPACE for pausing/resuming
[ERROR] [1669557755.364893365] [rosbag2_storage]: Could not open 'rosbag2_2022_11_27-23_02_35/rosbag2_2022_11_27-23_02_35_0' with 'mcap'. Error: unknown MCAP storage preset profile (valid options are 'fastwrite', 'zstd_fast', 'zstd_small'): none
[ERROR] [1669557755.364913668] [rosbag2_storage]: Could not load/open plugin with storage id 'mcap'
No storage could be initialized. Abort

❯ ros2 bag record -a -s mcap --storage-preset-profile fastwrite
usage: ros2 bag record [-h] [-a] [-e REGEX] [-x EXCLUDE] [--include-unpublished-topics] [--include-hidden-topics] [-o OUTPUT]
                       [-s {mcap,my_test_plugin,sqlite3}] [-f {s,a}] [--no-discovery] [-p POLLING_INTERVAL] [-b MAX_BAG_SIZE]
                       [-d MAX_BAG_DURATION] [--max-cache-size MAX_CACHE_SIZE] [--compression-mode {none,file,message}]
                       [--compression-format {zstd,fake_comp}] [--compression-queue-size COMPRESSION_QUEUE_SIZE]
                       [--compression-threads COMPRESSION_THREADS] [--snapshot-mode] [--ignore-leaf-topics]
                       [--qos-profile-overrides-path QOS_PROFILE_OVERRIDES_PATH] [--storage-preset-profile {none,resilient}]
                       [--storage-config-file STORAGE_CONFIG_FILE] [--start-paused] [--use-sim-time]
                       [topics ...]
ros2 bag record: error: argument --storage-preset-profile: invalid choice: 'fastwrite' (choose from 'none', 'resilient')
```
rosbag2 version
```
❯ apt-cache policy ros-humble-rosbag2
ros-humble-rosbag2:
  Installed: 0.15.3-1jammy.20221109.192253
  Candidate: 0.15.3-1jammy.20221109.192253
  Version table:
 *** 0.15.3-1jammy.20221109.192253 500
        500 http://packages.ros.org/ros2/ubuntu jammy/main amd64 Packages
        500 http://packages.ros.org/ros2-testing/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```
rosbag2_storage_mcap version
```
❯ apt-cache policy ros-humble-rosbag2-storage-mcap
ros-humble-rosbag2-storage-mcap:
  Installed: 0.5.0-1jammy.20221109.184113
  Candidate: 0.5.0-1jammy.20221109.184113
  Version table:
 *** 0.5.0-1jammy.20221109.184113 500
        500 http://packages.ros.org/ros2/ubuntu jammy/main amd64 Packages
        500 http://packages.ros.org/ros2-testing/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

### CODE REVIEW

**Comment by james-rms** [comment]
@wep21 thanks for the PR! Just FYI, i've merged and bloomed https://github.com/ros-tooling/rosbag2_storage_mcap/pull/86 which should also resolve the underlying issue.

**Review by MichaelOrlov — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/19a7ca0de8eeb73481593e8d9390bee8/raw/2cc1a3297b982cd094559d007ca1a6fea2bf7331/ros2.repos
BUILD args:  --packages-above-and-dependencies ros2bag rosbag2_storage_sqlite3 rosbag2_tests
TEST args:  --packages-above ros2bag rosbag2_storage_sqlite3 rosbag2_tests
ROS Distro: humble
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/11186
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17715/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12261/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18336/)

**Comment by MichaelOrlov** [comment]
It looks like some random unrelated error on CI.
Re-running CI jobs
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/11193
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17725/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12268/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18359/)

**Comment by MichaelOrlov** [comment]
It looks like some random unrelated error on CI.
Re-running CI jobs
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/11198
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17731/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12273/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18372/)

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/56384324a64241198a77f5e584fcba63/raw/2cc1a3297b982cd094559d007ca1a6fea2bf7331/ros2.repos
BUILD args:  --packages-above-and-dependencies ros2bag rosbag2_storage_default_plugins rosbag2_tests
TEST args:  --packages-above ros2bag rosbag2_storage_default_plugins rosbag2_tests
ROS Distro: humble
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/11206
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17740/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12282/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18384/)

**Pull request merged**
