### PR TITLE
Restructure test_play_timing

### PR DESCRIPTION
**Pull request by emersonknapp**
Related to https://github.com/ros2/rosbag2/issues/862

Separate all the test cases in test_play_timing, which should make the nightly failures slightly more clear. Not able to make this particular test fail in any manual run, so it seems like it might be specific to the circumstances of the nightly_repeated runs. Maybe excessive load on the servers.

### CODE REVIEW

**Comment by emersonknapp** [comment]
[Build Status](https://ci.ros2.org/job/ci_linux/15159/)

**Comment by emersonknapp** [comment]
Trying those same builds on unmodified rosbag2 

Everything: [Build Status](https://ci.ros2.org/job/ci_linux/15166/)

Transport only: [Build Status](https://ci.ros2.org/job/ci_linux/15167/)

**Comment by emersonknapp** [comment]
Everything again with Connext enabled this time to match nightly better [Build Status](https://ci.ros2.org/job/ci_linux/15175/)

**Review by lihui815 — APPROVED** [review]

**Comment by emersonknapp** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15189/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9909/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12869/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15368/)

**Pull request merged**
