### PR TITLE
Fix typo and composition link in README

### PR DESCRIPTION
**Pull request by christophebedard**
1. bandwith -> bandwidth
2. This link is not valid and doesn't really make sense (compile-time composition _using ROS services_?): https://docs.ros.org/en/rolling/Tutorials/Intermediate/Composition.html#compile-time-composition-using-ros-services). The section about compile-time composition is: https://docs.ros.org/en/rolling/Tutorials/Intermediate/Composition.html#compile-time-composition-with-hardcoded-nodes.

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI

**Review by MichaelOrlov — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
Changes only in the documentation. I don't think that we need to run CI.

**Comment by christophebedard** [comment]
I'll let anyone who has the necessary permissions merge this.

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport jazzy

**Pull request merged**
