### PR TITLE
Fix missing cstdint include when compiling with GCC13

### LINKED ISSUE #1379: GCC 13 missing cstdint include
Building with GCC13 fails due to a missing `#include <cstdint>` at https://github.com/ros2/rosbag2/blob/e552f15d35cc3318c21efeee4f03675d94545725/rosbag2_storage/include/rosbag2_storage/storage_options.hpp#L20

Without it, storage_options fails to compile at https://github.com/ros2/rosbag2/blob/e552f15d35cc3318c21efeee4f03675d94545725/rosbag2_storage/include/rosbag2_storage/storage_options.hpp#L35 and base_io_interface fails to compile at https://github.com/ros2/rosbag2/blob/e552f15d35cc3318c21efeee4f03675d94545725/rosbag2_storage/include/rosbag2_storage/storage_interfaces/base_io_interface.hpp#L28

### PR DESCRIPTION
**Pull request by yameatmeyourdead**
Fixes https://github.com/ros2/rosbag2/issues/1379

### CODE REVIEW

**Review by emersonknapp — APPROVED** [review]
LGTM

**Comment by emersonknapp** [comment]
Pulls: ros2/rosbag2#1383
Gist: https://gist.githubusercontent.com/emersonknapp/eaaabd7617f9367233194ef194de59dd/raw/b16b3335f3e0c0284b08e0fb8b9acc8518e917c5/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_storage
TEST args:  --packages-above rosbag2_storage
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12192
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18895/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13431/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19653/)

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport iron

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport humble

**Pull request merged**
