### PR TITLE
[galactic] Enable sanitizers only if code actually can run (#572)

### PR DESCRIPTION
**Pull request by jacobperron**
Backport #572 to Galactic.

### CODE REVIEW

**Review by gbiggs — APPROVED** [review]

**Comment by gbiggs** [comment]
CI:

- Linux [Build Status](https://ci.ros2.org/job/ci_linux/)
- Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/)
- Windows [Build Status](https://ci.ros2.org/job/ci_windows/)

**Comment by gbiggs** [comment]
The test failure doesn't look related to this PR.

**Review by emersonknapp — APPROVED** [review]

**Comment by jacobperron** [comment]
We're running a Rolling version of linters against Galactic, which I think is why we are seeing ament_cpplint and ament_uncrustify errors.

I haven't seen the `records_sensor_data` test failure before. It appears on both the ci.ros2.org job and the GPr job.

**Comment by jacobperron** [comment]
> I haven't seen the records_sensor_data test failure before. It appears on both the ci.ros2.org job and the GPr job.

Ah, it's a known flake: https://github.com/ros2/rosbag2/issues/766

**Comment by jacobperron** [comment]
@ros-pull-request-builder retest this please

**Comment by jacobperron** [comment]
See https://github.com/ros2/rosbag2/pull/959 for a fix for the lint CI.

**Pull request merged**
