### PR TITLE
[backport foxy-future] Reindexer (#641, #699)

### PR DESCRIPTION
**Pull request by emersonknapp**
Backport PRs #641 (reindexer functionality) and #699 (reindexer CLI) to foxy-future branch.

Related to #859

### CODE REVIEW

**Comment by emersonknapp** [comment]
Compatibility fixes in separate commit:

* rcutils Directory iteration didn't exist yet, so copy-pasted that implementation in-place for the backport.
* rcpputils::path operator / didn't allow for const, so worked around that
* No << operator for path, worked around that
* Added linter skipping for the C code which is not from the same standard

**Review by MichaelOrlov — COMMENTED** [review]
While implementation looks god for me, I would recommend to move compatibility related code which is corresponds to the https://github.com/ros2/rcutils/pull/323 to the separate files in the same `rosbag2_cpp` `include` and `src` folders. 
The rational  for that is that if someone in the future will try to backport https://github.com/ros2/rcutils/pull/323 the code will not compile until removing this workaround. And it will not pollute `reindexer.cpp`

**Comment by EsipovPA** [comment]
Is there some way to fix one last failed check? Looks like it is some kind of problem with signing-off commits

**Comment by emersonknapp** [comment]
That's not a blocking issue - more importantly it needs ci.ros2.org run on it

**Comment by emersonknapp** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15305/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10017/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12985/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15498/)

**Pull request closed without merging**
