### PR TITLE
[humble] Backport. Only pass one regular expression to filter topics

### PR DESCRIPTION
**Pull request by esteve**
This is a backport of #1053

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
@esteve CI failing in multiple tests related to the topics filtering https://build.ros2.org/job/Hpr__rosbag2__ubuntu_jammy_amd64/12/testReport/
Can you please address those failures?

**Review by MichaelOrlov — APPROVED** [review]
@esteve LGTM!

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/b29de6c1322bf7866e6e17dfaabb9ab9/raw/64c27e4e0f7db4b80613efe08693ea92a4f6a849/ros2.repos
BUILD args:  --packages-above-and-dependencies ros2bag rosbag2_py rosbag2_storage rosbag2_storage_default_plugins rosbag2_transport rosbag2_tests
TEST args:  --packages-above ros2bag rosbag2_py rosbag2_storage rosbag2_storage_default_plugins rosbag2_transport rosbag2_tests
ROS Distro: humble
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10616
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17081/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11634/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17502/)

**Comment by MichaelOrlov** [comment]
It seems failure on Windows build unrelated.
Running job one more time:
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17521/)

**Comment by MichaelOrlov** [comment]
@esteve It looks like we are making breaking `ABI` changes with #1039 and this PR #1054 in `humble`.
In particular [here](https://github.com/ros2/rosbag2/pull/1039/files#diff-8902dce2244f234ce070147eee8cf83d6935a354601447460903c954f572ea94R45) adding new field to the `player_options` data structure which is sort of interface on upper CPP layer.

I am afraid that we will have to even revert #1039.

@audrow Please advise if it's acceptable to make ABI breaking changes to `humble`?

**Comment by clalancette** [comment]
> @audrow Please advise if it's acceptable to make ABI breaking changes to `humble`?

No, definitely not.

**Comment by esteve** [comment]
> @esteve It looks like we are making breaking `ABI` changes with #1039 and this PR #1054 in `humble`. In particular [here](https://github.com/ros2/rosbag2/pull/1039/files#diff-8902dce2244f234ce070147eee8cf83d6935a354601447460903c954f572ea94R45) adding new field to the `player_options` data structure which is sort of interface on upper CPP layer.
> 
> I am afraid that we will have to even revert #1039.

It's unfortunate, but totally understandable. Thanks for looking into it.

**Comment by esteve** [comment]
Closing as this change would break ABI compatibility.

**Pull request closed without merging**
