### PR TITLE
Make some changes for newer versions of uncrustify

### PR DESCRIPTION
**Pull request by ahcorde**
Follow up of this PR https://github.com/ros2/rosbag2/pull/1578

I can see some failures here https://build.ros2.org/job/Rpr__rosbag2__ubuntu_noble_amd64/14/

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
@ahcorde A general comment instead of guarding a lot of code segments with the 
```
// *INDENT-OFF*
...
// *INDENT-ON*
```
statements it will be preferable to reformat everything with the new version of the Uncrustify.

cc: @clalancette It seems a nightmare with the new version of Uncrustify escalades more severely and more quickly than we assumed. The code formatting is going to diverge more significantly from previous  ROS 2 distros and it will be an extra burden during backporting.
It seems the idea for switching to the clang-format for core packages is not so bad. However, it seems nobody has time for this effort currently.

**Review by fujitatomoya — COMMENTED** [review]
i know this is still draft, but AFAIS those fix the uncrustify warnings. @MichaelOrlov 's comment needs to be discussed... :eyeglasses:

**Comment by clalancette** [comment]
So we still need to land https://github.com/ament/ament_lint/pull/475, which smooths over at least some of these differences.  I need to get back to that one, hopefully tomorrow.

**Comment by MichaelOrlov** [comment]
@clalancette Thanks for the update. In this case I would hold off from moving forward with this PR development.

**Comment by clalancette** [comment]
OK, so I ended up merging in https://github.com/ament/ament_lint/pull/475 today.  With that in place, as far as I can tell there are no uncrustify errors here.  @ahcorde Can you confirm that, and if that is the case for you, close this PR?  Thanks.

**Comment by ahcorde** [comment]
@clalancette I runned again the CI but I can still see some linter issues https://build.ros2.org/job/Rpr__rosbag2__ubuntu_noble_amd64/44/

**Comment by clalancette** [comment]
> @clalancette I runned again the CI but I can still see some linter issues https://build.ros2.org/job/Rpr__rosbag2__ubuntu_noble_amd64/44/

So the Rpr job is going to show the problem until we do a release of `ament_lint` into Rolling; I hope to do that early next week.

Can you test locally?

**Comment by MichaelOrlov** [comment]
@ahcorde According to the other [job failures](https://productionresultssa12.blob.core.windows.net/actions-results/534376b2-6303-4e7d-9176-e7e5e5925b38/workflow-job-run-5ceb2da2-285c-5143-78bc-b37abc043dd3/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-04-10T17%3A32%3A38Z&sig=yv90JUKM3ZuwvZd5yirDUQGAaGcKgHaLUHmPNZkwsGs%3D&sp=r&spr=https&sr=b&st=2024-04-10T17%3A22%3A33Z&sv=2021-12-02), it seems we have discrepancy only in two files for now. In the `rosbag2_transport/logging.hpp` and `rosbag2_transport/test_record.cpp`.
```
 >>>
2024-04-09T17:12:44.2346707Z build/rosbag2_transport/test_results/rosbag2_transport/uncrustify.xunit.xml: 57 tests, 0 errors, 2 failures, 0 skipped
2024-04-09T17:12:44.2347526Z - rosbag2_transport.uncrustify src/rosbag2_transport/logging.hpp
2024-04-09T17:12:44.2347947Z   <<< failure message
2024-04-09T17:12:44.2348194Z     Diff with 30 lines
2024-04-09T17:12:44.2348436Z   >>>
2024-04-09T17:12:44.2348815Z - rosbag2_transport.uncrustify test/rosbag2_transport/test_record.cpp
2024-04-09T17:12:44.2349248Z   <<< failure message
2024-04-09T17:12:44.2349567Z     Diff with 16 lines
2024-04-09T17:12:44.2349799Z   >>>
2024-04-09T17:12:44.2349917Z 
```
However, need to make a fresh run on Rolling for sure.

**Comment by clalancette** [comment]
> @ahcorde According to the other [job failures](https://productionresultssa12.blob.core.windows.net/actions-results/534376b2-6303-4e7d-9176-e7e5e5925b38/workflow-job-run-5ceb2da2-285c-5143-78bc-b37abc043dd3/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-04-10T17%3A32%3A38Z&sig=yv90JUKM3ZuwvZd5yirDUQGAaGcKgHaLUHmPNZkwsGs%3D&sp=r&spr=https&sr=b&st=2024-04-10T17%3A22%3A33Z&sv=2021-12-02), it seems we have discrepancy only in two files for now. In the `rosbag2_transport/logging.hpp` and `rosbag2_transport/test_record.cpp`.

Hm, that shouldn't be anymore.  I believe that at the moment, we should be uncrustify clean.  I'm running a job right now on Noble to check.

**Comment by MichaelOrlov** [comment]
- I've tried to reproduce on the latest Rolling build locally and my uncrustify is happy.
The errors reported before 
```
2024-04-09T17:12:44.2346707Z build/rosbag2_transport/test_results/rosbag2_transport/uncrustify.xunit.xml: 57 tests, 0 errors, 2 failures, 0 skipped
2024-04-09T17:12:44.2347526Z - rosbag2_transport.uncrustify src/rosbag2_transport/logging.hpp
2024-04-09T17:12:44.2347947Z   <<< failure message
2024-04-09T17:12:44.2348194Z     Diff with 30 lines
2024-04-09T17:12:44.2348436Z   >>>
2024-04-09T17:12:44.2348815Z - rosbag2_transport.uncrustify test/rosbag2_transport/test_record.cpp
2024-04-09T17:12:44.2349248Z   <<< failure message
2024-04-09T17:12:44.2349567Z     Diff with 16 lines
2024-04-09T17:12:44.2349799Z   >>>
2024-04-09T17:12:44.2349917Z 
```
was on the old branches before #1578

- Closing this PR as will not be merged since all uncrustify issues has already been addressed.

**Pull request closed without merging**
