### PR TITLE
use fastrtps static instead of dynamic

### PR DESCRIPTION
**Pull request by Karsten1987**
This is the CI for integrating rosbag2 into the `ros2.repos`.
The CI is using the default setup with having `Connext static` and `Fastrtps static` enabled:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/6805/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3101/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5596/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6630/)

Connected PR for repos file: 

Signed-off-by: Karsten Knese <karsten@openrobotics.org>

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The CI builds are showing a few test failures?

**Comment by Karsten1987** [comment]
Yes, I have to look into these. Mainly the end-to-end tests are difficult because not always all messages are received.

**Comment by Karsten1987** [comment]
In order to push forward, I disabled the flaky tests and increased time for discovery.
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/6818/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3112/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5606/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6640/)

**Comment by Karsten1987** [comment]
Putting this back in review. Increasing waiting time for discovery seemed to have solved the flaky test. The failures on aarch64 seem unrelated.

**Comment by clalancette** [comment]
> The failures on aarch64 seem unrelated.

Yeah, those are known flaky, so you can safely ignore them for now.

**Comment by Karsten1987** [comment]
Merging this, having the follow up work to re-enable the tests ticketed in #109

**Pull request merged**
