### PR TITLE
Disable adaptive qos subscription for now 

### PR DESCRIPTION
**Pull request by emersonknapp**
until we get it working on cyclone

Unblocks https://github.com/ros2/rosbag2/pull/345

Signed-off-by: Emerson Knapp <emerson.b.knapp@gmail.com>

### CODE REVIEW

**Comment by emersonknapp** [comment]
I think I'll do that in a separate PR. I'm working on it now using the `call_for_each_rmw_implementation` CMake macro (right approach?) but I'd like to get your changes unblocked as quickly and cleanly as possible.

I will just enable it on `rosbag2_transport` and `rosbag2_tests`, I agree that the rest should be independent of transport

**Comment by Karsten1987** [comment]
> I'm working on it now using the call_for_each_rmw_implementation CMake macro (right approach?) 

yes!

**Comment by emersonknapp** [comment]
FastRTPS run
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9905/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5522/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8058/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9757/)

CycloneDDS run
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9906/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5523/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8059/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9758/)

**Comment by emersonknapp** [comment]
FastRTPS
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9909/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5525/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8061/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9760/)

CycloneDDS
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9910/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5526/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8062/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9761/)

**Comment by emersonknapp** [comment]
The one failing test is the remaining unrelated zstd compression splitting. Merging now.

**Pull request merged**
