### PR TITLE
turn recorder into a node

### PR DESCRIPTION
**Pull request by Karsten1987**
One step closer to #716.

Turn the recorder into a node instead of accepting one.

### CODE REVIEW

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14310/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9100/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11996/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14415/)

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14311/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9101/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11997/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14416/)

**Review by emersonknapp — APPROVED** [review]
Great!

**Comment by emersonknapp** [comment]
Related to #685

**Pull request merged**
