### PR TITLE
Fix/futurize foxy dependency fixes

### LINKED ISSUE #698: Wrong include directories order
## Description
I've tried to build https://github.com/ros2/rosbag2/pull/687 to check if it works in our environment, but it seems it wont build clean if ros-foxy-rosbag2... packages are installed on the target machine.

I've checked it while building on host machine and reproduced in `ros:foxy` docker container. In both cases `colcon build` finishes with an error:
<details>
    <summary>ERROR</summary>

```
--- stderr: rosbag2_transport_future                                      
In file included from /ws/src/rosbag2_transport/test/rosbag2_transport/rosbag2_transport_test_fixture.hpp:42,
                 from /ws/src/rosbag2_transport/test/rosbag2_transport/record_integration_fixture.hpp:31,
                 from /ws/src/rosbag2_transport/test/rosbag2_transport/test_record_regex.cpp:24:
/ws/src/rosbag2_transport/test/rosbag2_transport/mock_sequential_reader.hpp:28:8: error: ‘void MockSequentialReader::open(const rosbag2_storage::StorageOptions&, const rosbag2_cpp::ConverterOptions&)’ marked ‘override’, but does not override
   28 |   void open(
      |        ^~~~
In file included from /ws/src/rosbag2_transport/test/rosbag2_transport/rosbag2_transport_test_fixture.hpp:43,
                 from /ws/src/rosbag2_transport/test/rosbag2_transport/record_integration_fixture.hpp:31,
                 from /ws/src/rosbag2_transport/test/rosbag2_transport/test_record_regex.cpp:24:
/ws/src/rosbag2_transport/test/rosbag2_transport/mock_sequential_writer.hpp:28:8: error: ‘void MockSequentialWriter::open(const rosbag2_storage::StorageOptions&, const rosbag2_cpp::ConverterOptions&)’ marked ‘override’, but does not override
   28 |   void open(
      |        ^~~~
In file included from /usr/include/c++/9/memory:80,
                 from /opt/ros/foxy/src/gmock_vendor/include/gmock/gmock-actions.h:45,
                 from /opt/ros/foxy/src/gmock_vendor/include/gmock/gmock.h:59,
                 from /ws/src/rosbag2_transport/test/rosbag2_transport/test_record_regex.cpp:15:
/usr/include/c++/9/bits/unique_ptr.h: In instantiation of ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = MockSequentialReader; _Args = {}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<MockSequentialReader, std::default_delete<MockSequentialReader> >]’:
/ws/src/rosbag2_transport/test/rosbag2_transport/rosbag2_transport_test_fixture.hpp:62:90:   required from here
/usr/include/c++/9/bits/unique_ptr.h:857:30: error: invalid new-expression of abstract class type ‘MockSequentialReader’
  857 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /ws/src/rosbag2_transport/test/rosbag2_transport/rosbag2_transport_test_fixture.hpp:42,
                 from /ws/src/rosbag2_transport/test/rosbag2_transport/record_integration_fixture.hpp:31,
                 from /ws/src/rosbag2_transport/test/rosbag2_transport/test_record_regex.cpp:24:
/ws/src/rosbag2_transport/test/rosbag2_transport/mock_sequential_reader.hpp:25:7: note:   because the following virtual functions are pure within ‘MockSequentialReader’:
   25 | class MockSequentialReader : public rosbag2_cpp::reader_interfaces::BaseReaderInterface
      |       ^~~~~~~~~~~~~~~~~~~~
In file included from /ws/src/rosbag2_transport/test/rosbag2_transport/mock_sequential_reader.hpp:23,
                 from /ws/src/rosbag2_transport/test/rosbag2_transport/rosbag2_transport_test_fixture.hpp:42,
                 from /ws/src/rosbag2_transport/test/rosbag2_transport/record_integration_fixture.hpp:31,
                 from /ws/src/rosbag2_transport/test/rosbag2_transport/test_record_regex.cpp:24:
/opt/ros/foxy/include/rosbag2_cpp/reader_interfaces/base_reader_interface.hpp:40:16: note:  ‘virtual void rosbag2_cpp::reader_interfaces::BaseReaderInterface::open(const rosbag2_cpp::StorageOptions&, const rosbag2_cpp::ConverterOptions&)’
   40 |   virtual void open(
      |                ^~~~
In file included from /usr/include/c++/9/memory:80,
                 from /opt/ros/foxy/src/gmock_vendor/include/gmock/gmock-actions.h:45,
                 from /opt/ros/foxy/src/gmock_vendor/include/gmock/gmock.h:59,
                 from /ws/src/rosbag2_transport/test/rosbag2_transport/test_record_regex.cpp:15:
/usr/include/c++/9/bits/unique_ptr.h: In instantiation of ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = MockSequentialWriter; _Args = {}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<MockSequentialWriter, std::default_delete<MockSequentialWriter> >]’:
/ws/src/rosbag2_transport/test/rosbag2_transport/rosbag2_transport_test_fixture.hpp:63:90:   required from here
/usr/include/c++/9/bits/unique_ptr.h:857:30: error: invalid new-expression of abstract class type ‘MockSequentialWriter’
  857 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /ws/src/rosbag2_transport/test/rosbag2_transport/rosbag2_transport_test_fixture.hpp:43,
                 from /ws/src/rosbag2_transport/test/rosbag2_transport/record_integration_fixture.hpp:31,
                 from /ws/src/rosbag2_transport/test/rosbag2_transport/test_record_regex.cpp:24:
/ws/src/rosbag2_transport/test/rosbag2_transport/mock_sequential_writer.hpp:25:7: note:   because the following virtual functions are pure within ‘MockSequentialWriter’:
   25 | class MockSequentialWriter : public rosbag2_cpp::writer_interfaces::BaseWriterInterface
      |       ^~~~~~~~~~~~~~~~~~~~
In file included from /ws/src/rosbag2_transport/test/rosbag2_transport/mock_sequential_writer.hpp:23,
                 from /ws/src/rosbag2_transport/test/rosbag2_transport/rosbag2_transport_test_fixture.hpp:43,
                 from /ws/src/rosbag2_transport/test/rosbag2_transport/record_integration_fixture.hpp:31,
                 from /ws/src/rosbag2_transport/test/rosbag2_transport/test_record_regex.cpp:24:
/opt/ros/foxy/include/rosbag2_cpp/writer_interfaces/base_writer_interface.hpp:37:16: note:  ‘virtual void rosbag2_cpp::writer_interfaces::BaseWriterInterface::open(const rosbag2_cpp::StorageOptions&, const rosbag2_cpp::ConverterOptions&)’
   37 |   virtual void open(
      |                ^~~~
make[2]: *** [CMakeFiles/test_record_regex__rmw_fastrtps_cpp.dir/build.make:63: CMakeFiles/test_record_regex__rmw_fastrtps_cpp.dir/test/rosbag2_transport/test_record_regex.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:512: CMakeFiles/test_record_regex__rmw_fastrtps_cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:141: all] Error 2
---
Failed   <<< rosbag2_transport_future [37.1s, exited with code 2]
```
</details>

For some reason `/opt/ros/foxy/include/rosbag2_cpp/writer_interfaces/base_writer_interface.hpp` header was selected  instead of `src/rosbag2_cpp/include/`, so I've build it with exported compile commands and found that [`test_record_regex`](https://github.com/ros2/rosbag2/blob/master/rosbag2_transport/CMakeLists.txt#L155) is compiled like:
```
{
  "directory": "/ws/build/rosbag2_transport_future",
  "command": "/usr/bin/c++  -DDEFAULT_RMW_IMPLEMENTATION=rmw_fastrtps_cpp -DPLUGINLIB__DISABLE_BOOST_FUNCTIONS -DRCUTILS_ENABLE_FAULT_INJECTION -DROS_PACKAGE_NAME=\\\"rosbag2_transport_future\\\" -DSPDLOG_COMPILED_LIB -I/opt/ros/foxy/src/gmock_vendor/include -I/opt/ros/foxy/src/gtest_vendor/include -I/ws/src/rosbag2_transport/include -isystem /ws/install/rosbag2_test_common_future/include -isystem /opt/ros/foxy/include -isystem /ws/install/rosbag2_compression_future/include -isystem /ws/install/rosbag2_cpp_future/include -isystem /ws/install/rosbag2_storage_future/include -isystem /opt/ros/foxy/opt/yaml_cpp_vendor/include -isystem /ws/install/shared_queues_vendor_future/include/moodycamel -isystem /ws/install/shared_queues_vendor_future/include    -Wall -Wextra -Wpedantic -Werror -std=gnu++14 -o CMakeFiles/test_record_regex__rmw_fastrtps_cpp.dir/test/rosbag2_transport/test_record_regex.cpp.o -c /ws/src/rosbag2_transport/test/rosbag2_transport/test_record_regex.cpp",
  "file": "/ws/src/rosbag2_transport/test/rosbag2_transport/test_record_regex.cpp"
}
```
Note than `-isystem /ws/install/rosbag2_cpp_future/include` goes AFTER `-isystem /opt/ros/foxy/include`
While for [`test_record`](https://github.com/ros2/rosbag2/blob/master/rosbag2_transport/CMakeLists.txt#L148) everything seems ok:
```
{
  "directory": "/ws/build/rosbag2_transport_future",
  "command": "/usr/bin/c++  -DDEFAULT_RMW_IMPLEMENTATION=rmw_fastrtps_cpp -DPLUGINLIB__DISABLE_BOOST_FUNCTIONS -DRCUTILS_ENABLE_FAULT_INJECTION -DROS_PACKAGE_NAME=\\\"rosbag2_transport_future\\\" -DSPDLOG_COMPILED_LIB -I/opt/ros/foxy/src/gmock_vendor/include -I/opt/ros/foxy/src/gtest_vendor/include -I/ws/src/rosbag2_transport/src/rosbag2_transport -I/ws/src/rosbag2_transport/include -isystem /ws/install/rosbag2_cpp_future/include -isystem /ws/install/rosbag2_storage_future/include -isystem /ws/install/rosbag2_test_common_future/include -isystem /opt/ros/foxy/include -isystem /opt/ros/foxy/opt/yaml_cpp_vendor/include -isystem /ws/install/rosbag2_compression_future/include -isystem /ws/install/shared_queues_vendor_future/include/moodycamel -isystem /ws/install/shared_queues_vendor_future/include    -Wall -Wextra -Wpedantic -Werror -std=gnu++14 -o CMakeFiles/test_record__rmw_fastrtps_cpp.dir/test/rosbag2_transport/test_record.cpp.o -c /ws/src/rosbag2_transport/test/rosbag2_transport/test_record.cpp",
  "file": "/ws/src/rosbag2_transport/test/rosbag2_transport/test_record.cpp"
}
```
Well, not truly ok, cuz `-isystem /opt/ros/foxy/include` still goes before other includes from workspace. But it compiles at least.

It seems that adding `rosbag2_cpp_future` to [`AMENT_DEPS` for `test_record_regex`](https://github.com/ros2/rosbag2/blob/master/rosbag2_transport/CMakeLists.txt#L158) moves `-isystem /ws/install/rosbag2_cpp_future/include` to position before `-isystem /opt/ros/foxy/include` but I am not sure it is right fix, cuz I dont know how does [`ament_target_dependencies`](https://github.com/ros2/rosbag2/blob/master/rosbag2_transport/cmake/rosbag2_transport_add_gmock.cmake#L60) work and how does it handle transitive dependencies. It might be a problem in ament cmake scripts

Observed behavior is not only for `rosbag2_transport_future` package. It seems that all compile commands for all packages should be reviewed, cuz this behavior might lead to very confusing bugs

### Expected Behavior
Everything compiles successfully and include directories order is right

### Actual Behavior
Error while compiling rosbag2 packages

## To Reproduce
1. Run ros container with rosbag2 inside:
```
docker run --rm -it ros:foxy /bin/bash
```
2. Install deps:
```
# Install deps
apt update && apt install ros-foxy-test-msgs pybind11-dev
```
3. Create workspace and clone rosbag2: 
```
mkdir -p ws/src
git clone https://github.com/ros2/rosbag2.git -b emersonknapp/futurize-foxy ws/src
cd ws
```
4. Build:
```
colcon build --ament-cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
```
5. Check for compile commands: `cat build/rosbag2_transport_future/compile_commands.json`

## System (please complete the following information)
 - OS: Ubuntu Bionic
 - ROS 2 Distro: foxy
 - Version: Reproduced in emersonknapp/futurize-foxy, but master branch still affected

### PR DESCRIPTION
**Pull request by hexonxons**
Fix #698 

Needs to be refactored after https://github.com/ros2/ros2/issues/1150

How to check if everything goes "OK":
* Build via `colcon build --ament-cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_ROSBAG2_BENCHMARKS=ON --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_ROSBAG2_BENCHMARKS=ON`
* Open `build/compile_commands.json`
* Test against regex `-((I)|(isystem))\s*/opt(?!((/ros/foxy/src/gmock)|(/ros/foxy/src/gtest))).*-((I)|(isystem))\s*/home`, where `/home` - first part of absolute path to local workspace

### CODE REVIEW

**Comment by emersonknapp** [comment]
When I tried to build this branch with the following sequence,

```
apt-get install ros-foxy-ros-base
source /opt/ros/foxy/setup.bash
colcon build --packages-up-to rosbag2
```

I still get the problem of reading globally installed dependencies before the local ones:

```
--- stderr: rosbag2_py
/ws/src/rosbag2/rosbag2_py/src/rosbag2_py/_reader.cpp: In member function ‘void rosbag2_py::Reader<T>::open(rosbag2_storage::StorageOptions&, rosbag2_cpp::ConverterOptions&)’:
/ws/src/rosbag2/rosbag2_py/src/rosbag2_py/_reader.cpp:47:19: error: cannot convert ‘rosbag2_storage::StorageOptions’ to ‘const rosbag2_cpp::StorageOptions&’
   47 |     reader_->open(storage_options, converter_options);
      |                   ^~~~~~~~~~~~~~~
      |                   |
      |                   rosbag2_storage::StorageOptions
In file included from /ws/src/rosbag2/rosbag2_py/src/rosbag2_py/_reader.cpp:24:
/opt/ros/foxy/include/rosbag2_cpp/reader.hpp:70:36: note:   initializing argument 1 of ‘void rosbag2_cpp::Reader::open(const rosbag2_cpp::StorageOptions&, const rosbag2_cpp::ConverterOptions&)’
   70 |   void open(const StorageOptions & storage_options, const ConverterOptions & converter_options);
      |             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/ws/src/rosbag2/rosbag2_py/src/rosbag2_py/_reader.cpp: In function ‘std::unordered_set<std::__cxx11::basic_string<char> > rosbag2_py::get_registered_readers()’:
```

Note `/opt/ros/foxy` header for the mismatched function declaration.

Am I missing something?

**Comment by hexonxons** [comment]
@emersonknapp 

Hmm, I can't reproduce on host Ubuntu 20.04 via
```
mkdir -p ws/src
git clone -b fix/futurize-foxy-dependency-fixes git@github.com:hexonxons/rosbag2.git ws/src/rosbag2
cd ws
source /opt/ros/foxy/setup.bash
colcon build --packages-up-to rosbag2
```

Did you checkout `fix/futurize-foxy-dependency-fixes` branch from my forked repo? Could you post `git remote show origin` output?

**Comment by emersonknapp** [comment]
It seems that I ran into the problem because I installed `ros-foxy-pybind11-vendor` instead of `pybind11-dev`. `rosbag2_py` depends on `pybind11_vendor`, and:

```
# rosdep resolve pybind11_vendor
#apt
ros-foxy-pybind11-vendor
```

I'll merge this into the main PR however as it is clearly much closer to the end goal

**Comment by emersonknapp** [comment]
I'll try to add an automated test case that builds while rosbag2 is installed in the underlay from apt - and we can try to figure out this one remaining issue. A user who does `rosdep install --from-paths` will hit this problem. It seems that if `ros-foxy-pybind11-vendor` is installed at all, then the `rosbag2_py` build picks up the `/opt/ros/foxy/include` path first.

**Pull request merged**
