### PR TITLE
Print "Hidden topics are not recorded" only once.

### PR DESCRIPTION
**Pull request by rshanor**
-Closes https://github.com/ros2/rosbag2/issues/1139

Signed-off-by: Rick Shanor <rickshanor@gmail.com>

### CODE REVIEW

**Review by MichaelOrlov — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/eb17b554d6961573f7b1a66633d06170/raw/d2223976aa02ad157706b32fb771737ac0078f79/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_transport
TEST args:  --packages-above rosbag2_transport
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/11314
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17862/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12430/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18533/)

**Comment by rshanor** [comment]
@MichaelOrlov anything else needed before merge? Thanks!

**Review by emersonknapp — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport humble

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport iron

**Pull request merged**
