### PR TITLE
Bugfix: Update metadata with new file_info before saving it the first time in the file

### PR DESCRIPTION
**Pull request by MichaelOrlov**
This PR is a bug fix for missing file_info for newly created file in saved metadata.

When we are switching to new storage, the correct behavior shall be as follows:
1. Save metadata to storage
2. Close current storage 
3. Open new storage for read_write
4. **Update metadata with a newly created file**
5. **Save metadata to storage**

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
@ros-pull-request-builder retest this please

**Review by christophebedard — APPROVED** [review]
Looks good to me with green CI.

**Comment by MichaelOrlov** [comment]
Pulls: ros2/rosbag2#1843
Gist: https://gist.githubusercontent.com/MichaelOrlov/9e3fdad4ca5ccf152d70e2b2ddfced12/raw/e9f907208e030ed0d619019b76d2f62f11d9917b/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_compression rosbag2_cpp rosbag2_tests
TEST args:  --packages-above rosbag2_compression rosbag2_cpp rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14778
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22082/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16339/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1601/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22817/)

**Comment by christophebedard** [comment]
Something weird happened in that Windows job

**Comment by ahcorde** [comment]
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22820/)

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport jazzy

**Pull request merged**
