### PR TITLE
Update upload-artifact into test.yml

### PR DESCRIPTION
**Pull request by mosfet80**
switch to node 20
node<20 is deprecaded

### CODE REVIEW

**Review by MichaelOrlov — APPROVED** [review]

**Review by christophebedard — APPROVED** [review]
This change can't currently be tested because of an unrelated test failure, but it looks good to me.

**Comment by MichaelOrlov** [comment]
Rebased to get the latest fix for CI failure and be able to test this PR.

**Comment by MichaelOrlov** [comment]
CI is green - merging then.

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport jazzy

**Pull request merged**
