### PR TITLE
Rosbag2 py

### PR DESCRIPTION
**Pull request by agutenkunst**
Considering that Foxy is supposed to stay until May 2023 I think adding rosbag2_py could help a lot of users.
This PR is primarly intented to open the discussion. 

Previously discussed in: https://github.com/ros2/rosbag2/pull/308#issuecomment-740143210

I think the opinion of @mabelzhang @jacobperron @mjeronimo @ros2/tooling-approvers is valueable here.

### CODE REVIEW

**Comment by jacobperron** [comment]
There is also https://github.com/ros2/rosbag2/pull/625, which is proposing a full backport `master` to `foxy` (possibly including rosbag2_py if all goes smoothly).

**Comment by agutenkunst** [comment]
Do you suggest a close of this draft PR in favor of #625 or are the PRs complementary such that this PR could be merged first?

The buildfarm seems to have a warning
```
Warning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
```

not sure what to make of it....

**Comment by emersonknapp** [comment]
> Do you suggest a close of this draft PR in favor of #625 or are the PRs complementary such that this PR could be merged first?

Yes, the suggestion is closing this PR in favor of #625, which contains everything currently on `rosbag2:master`. I'd prefer to wait until we resolve the conversation in https://discourse.ros.org/t/fast-forward-merging-rosbag2-master-api-to-foxy/18927/18 before making any major backports to Foxy (such as the full package `rosbag2_py`

**Comment by agutenkunst** [comment]
Ok closing

**Pull request closed without merging**
