### PR TITLE
[backport] disable plugins/tests which need rmw_fastrtps_cpp if unavailable (#137)

### PR DESCRIPTION
**Pull request by Karsten1987**
backport of #137 

Signed-off-by: ivanpauno <ivanpauno@ekumenlabs.com>

### CODE REVIEW

**Comment by Karsten1987** [comment]
as per https://github.com/ros2/rosbag2/pull/137#issuecomment-522138773, is there a way of triggering this PR for Connext individually opposed to its default RMW implementation?

**Comment by Karsten1987** [comment]
Connext only:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7934/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3968/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6459/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7783/)

**Comment by dirk-thomas** [comment]
> is there a way of triggering this PR for Connext individually opposed to its default RMW implementation?

No.

**Comment by ivanpauno** [comment]
> * Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3968/)

This one is failing because of unrelated reasons (I don't have an `aarch64` machine available for digging into the problem).

The others are unstable only because FastRTPS is not available (but it's at least building).

**Pull request merged**
