### PR TITLE
[Foxy-future] Avoid passing exception KeyboardInterrupt to the upper layer (backport #788)

### PR DESCRIPTION
**Pull request by bin-i**
* Avoid passing exception KeyboardInterrupt to the upper layer

Signed-off-by: Barry Xu <barry.xu@sony.com>

### CODE REVIEW

**Review by hidmic — APPROVED** [review]
LGTM pending green Foxy CI

**Review by emersonknapp — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/08720ed5cc33cee327474072790a4961/raw/57b590db04fa0ad173e81a54f8a7b674c5d509d2/ros2.repos
BUILD args:  --packages-above-and-dependencies ros2bag rosbag2_transport rosbag2_tests
TEST args:  --packages-above ros2bag rosbag2_transport rosbag2_tests
ROS Distro: foxy
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10617
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17082/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11635/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17503/)

**Comment by MichaelOrlov** [comment]
Trying to run build with `focal` Linux distribution
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17104/)

**Comment by MichaelOrlov** [comment]
Had to add `pybind11_vendor` to the .repos list, since it's not part of the default Foxy list and use `focal` Linux distro.
Rerun CI
Gist: https://gist.githubusercontent.com/MichaelOrlov/08720ed5cc33cee327474072790a4961/raw/57b590db04fa0ad173e81a54f8a7b674c5d509d2/ros2.repos
BUILD args:  --packages-above-and-dependencies ros2bag rosbag2_transport rosbag2_tests
TEST args:  --packages-above ros2bag rosbag2_transport rosbag2_tests
ROS Distro: foxy
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10861
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17355/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11890/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17850/)

**Comment by MichaelOrlov** [comment]
Some weird error on Linux CI job which is seems specific to the connext DDS, aka "unable to create participant".
Trying to rerun Linux job one more time
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17360/)

**Comment by MichaelOrlov** [comment]
@emersonknapp Do you remember if Connext DDS was ever running fine with `foxy-future` branch?
It seems some problem inside Connext DDS or its version.

**Comment by emersonknapp** [comment]
I don't remember ever actually using it, but it was definitely passing the tests when we created the branch.

**Comment by MichaelOrlov** [comment]
@emersonknapp The problem is that it is passing tests with CycloneDDS and FastRTPS and failing with ConnextDDS.

**Comment by MichaelOrlov** [comment]
CI tests failed with ConnextDDS due to expired license
**4: RTI Data Distribution Service Evaluation License issued to OSRF ... For non-production use only.
4: License Has Expired on 19-sep-2022**

From [CI build log](https://ci.ros2.org/job/ci_linux/17360/consoleText)
```
>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
4: This error state is being overwritten:
4: 
4:   'failed to create participant, at /home/jenkins-agent/workspace/ci_linux/ws/src/ros2/rmw_connext/rmw_connext_shared_cpp/src/node.cpp:318, at /home/jenkins-agent/workspace/ci_linux/ws/src/ros2/rcl/rcl/src/rcl/node.c:276'
4: 
4: with this new error message:
4: 
4:   'rcl node's rmw handle is invalid, at /home/jenkins-agent/workspace/ci_linux/ws/src/ros2/rcl/rcl/src/rcl/node.c:428'
4: 
4: rcutils_reset_error() should be called after error handling to avoid this.
4: <<<
4: [ERROR] [1663871346.831699987] [rcl]: Failed to fini publisher for node: 1
4: RTI Data Distribution Service Evaluation License issued to OSRF ... For non-production use only.
4: License Has Expired on 19-sep-2022
4: Please contact support@rti.com with any questions or comments.
4: DDSDomainParticipant_impl::create_disabledI:!create participant
4: DDSDomainParticipant_impl::createI:!create participant
```
@clalancette Could you please advise how to proceed with CI failure due to the outdated RTI license?

**Comment by clalancette** [comment]
> @clalancette Could you please advise how to proceed with CI failure due to the outdated RTI license?

We updated the license a couple of days ago.  A re-run of CI should fix it here.

**Comment by MichaelOrlov** [comment]
Trying to rerun Linux job one more time
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17414/)

**Pull request merged**
