### PR TITLE
fix logging signature

### PR DESCRIPTION
**Pull request by dirk-thomas**
Needs #104 to be merged.

Follow up of ros2/rcutils#154.

### CODE REVIEW

**Comment by Karsten1987** [comment]
I get line error warnings rosbag2_storage_default_plugins/logging.hpp

**Comment by Karsten1987** [comment]
oh, just a second too late :)

**Comment by dirk-thomas** [comment]
> I get line error warnings rosbag2_storage_default_plugins/logging.hpp

Please be more specific.

**Comment by Karsten1987** [comment]
Sorry, the changes introduced in this PR exceed the line length limits of 100 characters and cpplint complains.
It's addressed in here: https://github.com/ros2/rosbag2/pull/110

**Pull request merged**
