### PR TITLE
[backport, galactic] rosbag2_storage_mcap: merge into rosbag2 repo (#1163)

### PR DESCRIPTION
**Pull request by james-rms**

### CODE REVIEW

**Comment by clalancette** [comment]
I'm not totally convinced that we should do this for the older distributions.

It makes maintenance easier, but because it is not the default in the older distributions (and never will be), it seems like this will just make the situation murkier for those who want to use it.

That said, I don't have any fundamental objection here, so if the maintainers think this is better, go ahead with it.

**Comment by james-rms** [comment]
I think the code for the humble distribution of `rosbag2_storage_mcap` should live somewhere, and now https://github.com/ros-tooling/rosbag2_storage_mcap is archived :) I think it's best for the code to be all discoverable in one place.

**Comment by MichaelOrlov** [comment]
@ros-pull-request-builder retest this please

**Comment by james-rms** [comment]
Gist: https://gist.githubusercontent.com/james-rms/acde50a4d3aa8093b4e96cd1cf613c86/raw/2cfa5c77ccc57baed0f2f321ed6edb538407a5ca/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_storage_mcap rosbag2_tests
TEST args:  --packages-above rosbag2_storage_mcap rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/11196
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17729/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12271/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18370/)

**Pull request closed without merging**
