### PR TITLE
[humble] Update README with ros2 play services

### PR DESCRIPTION
**Pull request by saiaravind19**
Added Discription about ROS2 play Services in Readme file

### CODE REVIEW

**Review by emersonknapp — APPROVED** [review]
Looks good to me! Thanks for adding documentation. To make the CDO check happy, can you sign your commit with `git commit --amend --signoff`?

**Review by MichaelOrlov — APPROVED** [review]

**Comment by saiaravind19** [comment]
> Looks good to me! Thanks for adding documentation. To make the CDO check happy, can you sign your commit with `git commit --amend --signoff`?

@emersonknapp 
Hey I have updated added sign in my commit and will follow in the future commits.

If you dont mind can I know what is the holding the merge request.
I am new to this process so please excuse my silly doubts.

**Comment by MichaelOrlov** [comment]
@saiaravind19 The workflow usually is to create PR for rolling and then backport it to the other distros like Iron and Humble.
Could you please rebase your branch or create one more similar PR for Rolling?

**Comment by saiaravind19** [comment]
@MichaelOrlov  I have checked README for rolling it is up-to date with all rosbag play services documented. 
Humble branch is missing documentation of these services.

**Comment by MichaelOrlov** [comment]
@saiaravind19 Sorry. I missed it. You are good.

**Pull request merged**
