### PR TITLE
[backport foxy] Fixed playing if unknown message types exist (#592)

### PR DESCRIPTION
**Pull request by emersonknapp**
Backport #592

### CODE REVIEW

**Review by zmichaels11 — DISMISSED** [review]

**Comment by emersonknapp** [comment]
Gist: https://gist.githubusercontent.com/emersonknapp/b007e248c10680d7d4063747912dcd0b/raw/92c1c4a46de5ba30fdeea22015bd996d8d0efe2c/ros2.repos
BUILD args: --packages-up-to rosbag2_transport rosbag2_tests
TEST args: --packages-select rosbag2_transport rosbag2_tests
Job: ci_launcher

**Comment by emersonknapp** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14748/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9498/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12412/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14895/)

**Comment by emersonknapp** [comment]
Gist: https://gist.githubusercontent.com/emersonknapp/4a27fcdf674c92c13f7f88b910a4e24a/raw/73179e3941d7f1b8f4797dfbd356266f7ab3f1c1/ros2.repos
BUILD args: --packages-up-to rosbag2 rosbag2_transport rosbag2_tests
TEST args: --packages-select rosbag2 rosbag2_transport rosbag2_tests
ROS Distro: foxy
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/8675
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14861/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9611/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12528/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15020/)

**Review by zmichaels11 — APPROVED** [review]

**Comment by emersonknapp** [comment]
Waiting for https://github.com/ros2/rosbag2/pull/686, then a retest - to make sure this backport is not introducing any new instability.

**Comment by emersonknapp** [comment]
Waiting for #818 which should clean up the last failing test - want to have 0 failing tests before merging this

**Comment by emersonknapp** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14864/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9614/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12531/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15023/)

**Pull request merged**
