### PR TITLE
Replace TSAUniqueLock implementation with rcpputils::unique_lock

### PR DESCRIPTION
**Pull request by emersonknapp**
Depends on https://github.com/ros2/rcpputils/pull/180

### CODE REVIEW

**Review by MichaelOrlov — APPROVED** [review]
LGTM

**Comment by clalancette** [comment]
Now that we've merged in https://github.com/ros2/rcpputils/pull/180, here is CI just for this PR:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19458/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13981/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20181/)

**Comment by MichaelOrlov** [comment]
@clalancette I see that `build_and_test` and `rpr` jobs start failing due to the missing dependencies from the `rcpputils` package.
```
2023-08-30T22:47:58.7041799Z /__w/rosbag2/rosbag2/ros_ws/src/j82kidnpuu/rosbag2/rosbag2_cpp/src/rosbag2_cpp/clocks/time_controller_clock.cpp:22:10: fatal error: rcpputils/unique_lock.hpp: No such file or directory
2023-08-30T22:47:58.7042298Z    22 | #include "rcpputils/unique_lock.hpp"
```
How long it could take for the missing dependencies to be available?

**Comment by clalancette** [comment]
> How long it could take for the missing dependencies to be available?

I'm planning on doing a series of releases tomorrow, which should take about 12 hours to make it through the build system.  Assuming I don't run into issues, I think it should be fixed by the end of the week.

**Comment by MichaelOrlov** [comment]
@clalancette Thank, sounds good.

**Pull request merged**
