### PR TITLE
[Jazzy] Release 0.26.5

### PR DESCRIPTION
**Pull request by marcoag**
Once this is approved, I'll squash merge it onto the `jazzy` branch, add the `0.26.5` tag, and bloom-release it.

### CODE REVIEW

**Comment by marcoag** [comment]
Force pushed to fix DCO.

**Review by MichaelOrlov — COMMENTED** [review]
@marcoag The content looks good to me. However, I don't see a corresponding **0.26.5** tag in the repo.

**Comment by marcoag** [comment]
I'll tag the commit that get's generated when squash merging this into the jazzy branch, should it be done in a different way?

**Comment by MichaelOrlov** [comment]
Ahh, ok, usually `catkin_prepare_release` automatically creates tags.
Approving then.

**Review by MichaelOrlov — APPROVED** [review]

**Comment by marcoag** [comment]
> Ahh, ok, usually `catkin_prepare_release` automatically creates tags. Approving then.

yup, but since we do this one through PR I believe the usual way is to create it once merged (or at least that's how I did before).

**Pull request merged**
