### PR TITLE
Fix a bug on parsing wrong description in plugin xml file

### PR DESCRIPTION
**Pull request by Barry-Xu-2018**
Related to issue #577

### CODE REVIEW

**Review by emersonknapp — APPROVED** [review]
Thanks for the patch!

**Comment by Barry-Xu-2018** [comment]
@emersonknapp 

CI system seems to be unstable.  I re-push code without change. 
Test passed this time.

**Comment by emersonknapp** [comment]
Gist: https://gist.githubusercontent.com/emersonknapp/5a836468b12517403267db8621ef41b6/raw/e2d0c3bb1539444f3d0a9e2daf17137db36a8bb4/ros2.repos
BUILD args: --packages-up-to ros2bag
TEST args: --packages-select ros2bag
Job: ci_launcher


* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13241/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8172/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10955/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13272/)

**Comment by emersonknapp** [comment]
Windows instability is fixed on master

**Pull request merged**
