### PR TITLE
Revert "Make sure published messages are acknowledged for play mode"

### PR DESCRIPTION
**Pull request by jhdcs**
Reverts ros2/rosbag2#951

### CODE REVIEW

**Comment by jhdcs** [comment]
PR was merged before CI was run. My fault.

**Comment by clalancette** [comment]
Just FYI, I'm fine with running CI on the current state of things (not including this revert), and just posting it to #951.  If it passes, great, then we can just close this one.  If not, we can merge this and then take our time to fix any issues.

**Comment by jhdcs** [comment]
That would certainly make things much easier... How do I run CI?

**Comment by clalancette** [comment]
> That would certainly make things much easier... How do I run CI?

You need to log in to https://ci.ros2.org, and run the https://ci.ros2.org/job/ci_launcher/ job with the appropriate options to choose the branch in question, and use the appropriate colcon options.  That job will spit out some text that you can copy-n-paste into a comment here.

**Comment by jhdcs** [comment]
Do I need special permissions on Jenkins' side? I'm not seeing where to run the job...

**Comment by clalancette** [comment]
> Do I need special permissions on Jenkins' side? I'm not seeing where to run the job...

Yeah, you need special permission if you haven't been given it before.  I'm happy to run this one for you (I'll go do that now), but you are going to be doing a bunch of development/reviewing on this repository, we should probably talk offline about getting you access.

**Comment by clalancette** [comment]
OK, CI over in #951 was good, so we can close this out.

**Pull request closed without merging**
