### PR TITLE
[Foxy Backport]  use interface_include_directories #426

### PR DESCRIPTION
**Pull request by Karsten1987**
backport of https://github.com/ros2/rosbag2/pull/426

### CODE REVIEW

**Comment by emersonknapp** [comment]
Is the "Fpr__rosbag2__ubuntu_focal_amd64" job sufficient for our CI needs on these backports, or should we also be doing full CI runs against the other supported platforms?

**Comment by emersonknapp** [comment]
Also, we should possible add branch protection to the distro branches to require at least 1 approving review before merge. What do you think? I don't have admin access to this repo so I can't just go do it.

**Comment by Karsten1987** [comment]
I think it's safe, given that all commits on master got backported already. With this backport, master is equivalent to foxy.

**Comment by Karsten1987** [comment]
@emersonknapp fyi, I enabled branch protection on foxy

**Pull request merged**
