### PR TITLE
Bugfix for parameters not passing to recorder's node from child component

### PR DESCRIPTION
**Pull request by roncapat**
I discovered that when deriving `Recorder` to craft a dynamically-loadable Component (See #902 and https://github.com/berndpfrommer/rosbag2_composable_recorder) there is a problem with parameter configuration.

In particular:
- if launched as standalone executable, parameter specified via yaml or command line are correctly applied.
- if loaded in a component container, parameters are not applied

I tracked down this issue to the single line of this patch. Basically, it seems that defining a brand new parameter_override vector wipes out the parameters I'm not 100% sure, but seems like in general parameters are passed to a component as overrides.

This single line patch ensures not to drop overrides added to the vector from child classes of `Recorder`. 

I have to check, but maybe around the repo there may be similar issues.

### CODE REVIEW

**Comment by Fixit-Davide** [comment]
> I tracked down this issue to the single line of this patch. Basically, it seems that defining a brand new parameter_override vector wipes out the parameters I'm not 100% sure, but seems like in general parameters are passed to a component as overrides.

See here for confirmation: https://github.com/ros2/rclcpp/blob/f8072f2fa265000a2a1be8f3dbe7e04d9dfb1c91/rclcpp_components/src/component_manager.cpp#L137-L166

**Comment by MichaelOrlov** [comment]
@roncapat Can you write a simple regression unit test to cover this changes?

**Comment by roncapat** [comment]
@MichaelOrlov here you are :)

**Review by MichaelOrlov — APPROVED** [review]
@roncapat Too long to write. See my commit https://github.com/ros2/rosbag2/pull/1360/commits/6a5d643c42c5c4e3f621957f58bfdf93f5c6735a

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/34eba218c7e58164a34f27ac6a59c2a0/raw/6210585001be9ded50b5428ec02416c6c5cd3a37/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_transport
TEST args:  --packages-above rosbag2_transport
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12150
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18845/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13386/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19598/)

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport humble

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport iron

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2023-06-15/32038/1

**Pull request merged**
