### PR TITLE
Update maintainer list for Eloquent

### PR DESCRIPTION
**Pull request by mjeronimo**
Signed-off-by: Michael Jeronimo <michael.jeronimo@openrobotics.org>

### CODE REVIEW

**Review by Karsten1987 — APPROVED** [review]

**Review by Karsten1987 — APPROVED** [review]

**Review by emersonknapp — APPROVED** [review]

**Comment by mjeronimo** [comment]
@ros-pull-request-builder retest this please

**Comment by emersonknapp** [comment]
Weird, test isn't actually failing, it looks like the PR builder is triggering on LSan output? http://build.ros2.org/job/Epr__rosbag2__ubuntu_bionic_amd64/199/testReport/(root)/projectroot/test_ros2_message/

**Comment by mjeronimo** [comment]
Yes, definitely strange. I haven't been able to figure this one out yet.

**Comment by mjeronimo** [comment]
@ros-pull-request-builder retest this please

**Pull request merged**
