### PR TITLE
rosbag2_py: set defaults for config when bag rewriting

### LINKED ISSUE #1119: `ros2 bag convert` with compression can drop messages
## Description
`ros2 bag convert` with message-level compression will silently write only some messages to the output bag.

### Expected Behavior
`ros2 bag convert` will convert bags at slower-than-real-time if neccessary, blocking on a full queue (rather than dropping messages).

Even if this can't be done, I would expect to see a warning if i'm dropping messages while converting.

### Actual Behavior
ROS2 bag convert appears to drop messages.

## To Reproduce
Grab a sample MCAP bag here: https://github.com/foxglove/mcap/blob/main/testdata/mcap/demo.mcap (uses ROS1 messages, but `ros2 bag convert` does not care)
```bash
$ cat << EOF > convert.yaml
output_bags:
  - uri: message_compressed_sqlite3
    compression_mode: message
    compression_format: zstd
    all: true
EOF
$ ros2 bag convert -i demo.mcap -o convert.yaml
# observe difference in message count
$ ros2 bag info demo.mcap

closing.

Files:             demo.mcap
Bag size:          58.6 MiB
Storage id:        mcap
Duration:          7.780s
Start:             Mar 22 2017 13:26:20.103 (1490149580.103)
End:               Mar 22 2017 13:26:27.884 (1490149587.884)
Messages:          1606
Topic information: Topic: /velodyne_points | Type: sensor_msgs/PointCloud2 | Count: 78 | Serialization Format: ros1
                   Topic: /radar/tracks | Type: radar_driver/RadarTracks | Count: 156 | Serialization Format: ros1
                   Topic: /radar/range | Type: sensor_msgs/Range | Count: 156 | Serialization Format: ros1
                   Topic: /radar/points | Type: sensor_msgs/PointCloud2 | Count: 156 | Serialization Format: ros1
                   Topic: /tf | Type: tf2_msgs/TFMessage | Count: 774 | Serialization Format: ros1
                   Topic: /image_color/compressed | Type: sensor_msgs/CompressedImage | Count: 234 | Serialization Format: ros1
                   Topic: /diagnostics | Type: diagnostic_msgs/DiagnosticArray | Count: 52 | Serialization Format: ros1
# missing many messages
$ ros2 bag info message_compressed_sqlite3
Files:             message_compressed_sqlite3_0.db3
Bag size:          4.3 MiB
Storage id:        sqlite3
Duration:          7.780s
Start:             Mar 22 2017 13:26:20.103 (1490149580.103)
End:               Mar 22 2017 13:26:27.884 (1490149587.884)
Messages:          62
Topic information: Topic: /diagnostics | Type: diagnostic_msgs/DiagnosticArray | Count: 2 | Serialization Format: ros1
                   Topic: /image_color/compressed | Type: sensor_msgs/CompressedImage | Count: 8 | Serialization Format: ros1
                   Topic: /radar/points | Type: sensor_msgs/PointCloud2 | Count: 8 | Serialization Format: ros1
                   Topic: /radar/range | Type: sensor_msgs/Range | Count: 7 | Serialization Format: ros1
                   Topic: /tf | Type: tf2_msgs/TFMessage | Count: 29 | Serialization Format: ros1
                   Topic: /velodyne_points | Type: sensor_msgs/PointCloud2 | Count: 8 | Serialization Format: ros1
```

Using `compression_queue_size: 1000` alleviates this issue for this bag, but not clear if this is sufficient for all bags.
## System (please complete the following information)
 - OS: Ubuntu 22.04 ARM64 running in Parallels on an M1 Macbook
 - ROS 2 Distro: Rolling
 - Version: 626d69bafd9a8fb922dc2ec9cb59c80d00e6d56f

### PR DESCRIPTION
**Pull request by james-rms**
Signed-off-by: James Smith <james@foxglove.dev>

Fixes #1119

### CODE REVIEW

**Review by MichaelOrlov — APPROVED** [review]
@james-rms Thanks for proposed fix.
LGTM.

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/37b035b3dac90791e769a837018b63ec/raw/838c31c160cc15706657ec6aecb273077a52baeb/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_py ros2bag rosbag2_tests
TEST args:  --packages-above rosbag2_py ros2bag rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10967
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17473/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12002/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18013/)

**Comment by MichaelOrlov** [comment]
@james-rms I see a lot of new warnings on Windows build about multiple inclusions of the `YAML_CPP`.
Those warnings supposed to be fixed in the https://github.com/ros2/rosbag2/pull/964

I am curios about if your branch behind the latest rolling and doesn't contain fixes from https://github.com/ros2/rosbag2/pull/964 ?
If so could you please rebase your branch on top of latest `rolling` branch?

**Comment by james-rms** [comment]
@MichaelOrlov my merge base is c58d73ce1391d814a2331da5ea65b27bc2931765 from 29 Sept, it should contain those fixes.

**Comment by james-rms** [comment]
@MichaelOrlov I updated the patch to be type-safe, please let me know what you think.

**Comment by MichaelOrlov** [comment]
@james-rms I am sorry I don't get it. 
What are you trying to solve with type safe update? 
And what a difference when calling `YAML::convert::decode(bag_node, record_options);` explicitly?

**Comment by james-rms** [comment]
@MichaelOrlov here if `compression_queue_size` is removed or changes name, the code will no longer compile (rather than just setting a field on a YAML node that nobody reads).

**Comment by MichaelOrlov** [comment]
@james-rms Ok good. Can we do the same for `StorageOptions`?
`auto storage_options = bag_node.as<rosbag2_storage::StorageOptions>();`

**Review by MichaelOrlov — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
@james-rms BTW there are a couple new warnings from gcc 
`qualified-id in declaration before ‘(’ token 268 | YAML::convert::decode(bag_node, record_options); | ^` 
We need to address them before moving forward.

**Comment by MichaelOrlov** [comment]
Trying to re-run CI after updates:
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10974
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17483/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12010/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18031/)

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2022-10-13/28213/1

**Pull request merged**
