### PR TITLE
switch to not deprecated API

### PR DESCRIPTION
**Pull request by dirk-thomas**
Related to ros2/ros2cli#436.

### CODE REVIEW

**Comment by zmichaels11** [comment]
This is causing an error in build & test: `Failed to load entry point 'bag': cannot import name 'add_subparsers_on_demand'`

**Comment by dirk-thomas** [comment]
@zmichaels11 This needs to be tested against the branch of the referenced PR in order to pass.

**Comment by dirk-thomas** [comment]
@zmichaels11 With the referenced PR being merged can you please retrigger the failing action.

**Comment by dirk-thomas** [comment]
Technically this one will need a minimum version dependency on the next version of `ros2cli`.

**Pull request merged**
