### PR TITLE
Backport "Make unpublished topics unrecorded by default" (Issue #967) to Humble

### PR DESCRIPTION
**Pull request by theseankelly**
This pull request is a backport of the fix for #967 from Rolling to Humble.

See PR #968 for additional details.

### CODE REVIEW

**Review by audrow — APPROVED** [review]

**Review by MichaelOrlov — APPROVED** [review]

**Comment by gbiggs** [comment]
CI:

- Linux [Build Status](https://ci.ros2.org/job/ci_linux/16686/)
- Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/11273/)
- Windows [Build Status](https://ci.ros2.org/job/ci_windows/17087/)

**Review by jhdcs — APPROVED** [review]

**Comment by theseankelly** [comment]
Hey @jhdcs @audrow @MichaelOrlov just wanted to follow up on this -- we'd really appreciate getting this into Humble as it directly impacts our daily workflows. Not to be a nag -- just realizing we're getting very close to the cutoff date mentioned in the other PR.

**Comment by theseankelly** [comment]
Hey @audrow will this package be tagged and included in this week's [humble sync](https://discourse.ros.org/t/preparing-for-humble-sync-on-july-15th/26452)?

**Comment by MichaelOrlov** [comment]
@audrow What needs to be done to include rosbag2 in [humble sync](https://discourse.ros.org/t/preparing-for-humble-sync-on-july-15th/26452) ?

**Comment by theseankelly** [comment]
Looks like the sync was missed

**Pull request merged**
