### PR TITLE
Add the ability to record any key/value pair in 'custom' field in metadata.yaml

### PR DESCRIPTION
**Pull request by allenh1**
This restores the changes from #976 that were reverted in #984.

Additionally, a fix was added to correct the destruction order in `SequentialCompressionWriterTest`.

https://github.com/ros2/rosbag2/blob/e1f4349f33aaef1bf0fb13625cf23d80f9af2de0/rosbag2_compression/test/rosbag2_compression/test_sequential_compression_writer.cpp#L61-L64

The `write_metadata` call registered by the above hook is being invoked by the destructor for `writer_`. At this point, however, the `intercepted_metadata_` object has already been destructed, leading to a segv.

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/f369c45f7fc66b7ec4d59dfa09eb0893/raw/e532c13f7dc3a8293cf61bfe23856d7524753c4a/ros2.repos
BUILD args:  --packages-above-and-dependencies ros2bag rosbag2_cpp rosbag2_py rosbag2_storage rosbag2_compression rosbag2_tests
TEST args:  --packages-above ros2bag rosbag2_cpp rosbag2_py rosbag2_storage rosbag2_compression rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10475
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16919/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11485/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17318/)

**Review by MichaelOrlov — APPROVED** [review]
@allenh1 Thanks for your contribution and fixing issue with Windows build!
LGTM.

**Review by MichaelOrlov — CHANGES_REQUESTED** [review]
@allenh1 Unfortunately CI build got failed, but now in another place.
`SequentialWriterTest.split_event_calls_callback`
Could you please try to figure out why it fails.

@gbiggs Could you please help with analysis in  `SequentialWriterTest.split_event_calls_callback` test failure, it was recently added by you.

**Comment by allenh1** [comment]
@MichaelOrlov Should be fixed now.

**Comment by MichaelOrlov** [comment]
Re-run CI:
Gist: https://gist.githubusercontent.com/MichaelOrlov/f369c45f7fc66b7ec4d59dfa09eb0893/raw/e532c13f7dc3a8293cf61bfe23856d7524753c4a/ros2.repos
BUILD args:  --packages-above-and-dependencies ros2bag rosbag2_cpp rosbag2_py rosbag2_storage rosbag2_compression rosbag2_tests
TEST args:  --packages-above ros2bag rosbag2_cpp rosbag2_py rosbag2_storage rosbag2_compression rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10486
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16932/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11496/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17329/)

**Review by MichaelOrlov — APPROVED** [review]

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-8-18-2022/27050/1

**Pull request merged**
