### PR TITLE
Add filter verb

### PR DESCRIPTION
**Pull request by wep21**
I added filter verb to filter topics with python expression.

### CODE REVIEW

**Comment by wep21** [comment]
@emersonknapp Could you review this?

**Review by emersonknapp — COMMENTED** [review]
While I think this is a useful feature - I think that it can be built a little more generically.

@gbiggs is currently working on https://github.com/ros2/rosbag2/issues/831. This `ros2 bag convert` feature could take the filter as an extra argument, rather than having a whole separate verb `ros2 bag filter`.

I would like to hold off on reviewing this PR until we have that base feature in place, so that we could build this as a simple extension to it. Because of this, I won't leave my full comments here (I would have commented on hardcoding `cdr` for the StorageOptions, for example. And I would say that we need tests, and control over the StorageOptions for the output bag. However, if the generic feature is built first, then this won't have to worry about most of that)

I'll try to see about the timeline on that feature. To accelerate development we may put in the singular bag->bag version first, then move on to the multi-bag implementation.

**Comment by wep21** [comment]
Closed by #921.

**Comment by emersonknapp** [comment]
A note that #921 doesn't support arbitrary Python expression. It only supports filtering in the sense of choosing which topic names to forward.

This PR is more related to https://github.com/ros2/rosbag2/issues/885, which is still open at this point.

**Pull request closed without merging**
