### PR TITLE
Redesign Player class with PIMPL idiom

### PR DESCRIPTION
**Pull request by roncapat**
Prerequisite of #1419, to allow more elegant parameter parsing and constructor chaining.
Recorder has already PIMPL implementation, so this is also to align the codebase.

### CODE REVIEW

**Comment by roncapat** [comment]
Nest: Need to fix access to PIMPLed variables from MockPlayer

**Comment by MichaelOrlov** [comment]
@roncapat Does this PR still in the WIP (Work In Progress) stage?  
I see a bunch of test failures in the player in the [build_and_test](https://github.com/ros2/rosbag2/actions/runs/6075809816/job/16482718369?pr=1447) CI job

**Comment by roncapat** [comment]
@MichaelOrlov yep sorry, I haven't forgot about these, it's just a complex time at work. I'll be back on this as soon as I can :) I'll mark it again as draft, pending some manual testing ( I struggle to understand from CI output where the problem might be).

In the meantime, if you want, may I ask you to check especially how I had to modify the mock player / which protected methods I had to add to Player in order to let the mock player compile again?

**Comment by MichaelOrlov** [comment]
Hi @roncapat, no worries. I want to move forward with this PR and ready to help and contribute.
I've made a thorough review and prepared all required fixes to be ready to move forward and merge this branch to the master.
Please see my PR on your repo https://github.com/roncapat/rosbag2/pull/2

But before merging my PR on your branch please fix `DCO` for your commits on your branch! 
After that, I will rebase my branch and then you will be able to safely merge changes from my PR and I will approve and run the full CI before merge on master.

To add your Signed-off-by line to every commit in this branch:
Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: git rebase HEAD~17 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin patch-3

**Comment by roncapat** [comment]
Just give me 24 hours and it will be done, very appreciated! :)

**Comment by MichaelOrlov** [comment]
Sure - take your time.

**Comment by roncapat** [comment]
@MichaelOrlov all CI jobs look good now (thanks for the fixes!!).

**Review by MichaelOrlov — APPROVED** [review]
@roncapat Thank you for your contribution.
LGTM.

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/a39fb5e49cd1ed0fb04bc24093496a17/raw/21b5269f54d30e1fe81dc645ead0a147d9f1f06f/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_transport rosbag2_tests
TEST args:  --packages-above rosbag2_transport rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12680
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19536/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14055/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20256/)

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2023-09-21/33733/1

**Pull request merged**
