### PR TITLE
rosbag2_py pybind wrapper for "record" - remove rosbag2_transport_py

### PR DESCRIPTION
**Pull request by emersonknapp**
Depends on #693 

Followup to `rosbag2_py::Player`

Add a `rosbag2_py::Recorder` - and expose `RecordOptions` to Python. Remove `rosbag2_transport_python.cpp` - it is fully replaced.

### CODE REVIEW

**Review by Karsten1987 — APPROVED** [review]
sweet!

LGTM with green CI.

**Comment by emersonknapp** [comment]
Gist: https://gist.githubusercontent.com/emersonknapp/e82c17523b5d1535935dc776b2246fc9/raw/dc1536d0818be644c16e0d3e7341e1f4c8107608/ros2.repos
BUILD args: --packages-up-to rosbag2_tests rosbag2_transport ros2bag rosbag2_py rosbag2
TEST args: --packages-select rosbag2_tests rosbag2_transport ros2bag rosbag2_py rosbag2
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/8045
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14160/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8959/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11840/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14258/)

**Comment by emersonknapp** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14169/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8968/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11850/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14269/)

**Comment by emersonknapp** [comment]
Windows cmake warning is unrelated - it's from the rti cmake module

**Comment by Karsten1987** [comment]
it looks like that change introduced a regression on the tests. We see the same test failures on all platforms:
https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/1559/testReport/junit/(root)/projectroot/test_transport_py/

**Comment by emersonknapp** [comment]
That's no good - I am looking into it

**Comment by Karsten1987** [comment]
according to  @sloretz we might want to get rid of pycapsules completely:
We're using the pycapsules QoS here: https://github.com/ros2/rosbag2/pull/702/files#diff-c85fd024e7d68c762d60d25e2ba155bcc527f04c937ed09adc893ea241fdc61cR45 but apparently that got removed.

see https://github.com/ros2/rclpy/pull/741/files

**Comment by emersonknapp** [comment]
Oh - we must have had a race condition in that I ran my CI before that got pushed. Thanks for the context. I am thinking that I would prefer to patch fix this instead of revert, right now.

**Pull request merged**
