### PR TITLE
Add windows to build matrix

### LINKED ISSUE #316: Enable Windows CI in GitHub Actions
## Description
[action-ros-ci](https://github.com/ros-tooling/action-ros-ci) supports building on Windows. It should be used to build `rosbag2` periodically and on PRs. (same as Linux CI) 

## Completion Criteria
- [ ] Add Windows CI that builds and tests `rosbag2`

## Implementation Notes / Suggestions
* `rosbag2_tests` [is flaky on Windows](https://github.com/ros2/rosbag2/issues/305) due to relying on programmatically sending `SIGINT` to a subprocess.

### PR DESCRIPTION
**Pull request by piraka9011**
Add Windows to the build and test workflow.

Closes #316 

Signed-off-by: Anas Abou Allaban <aabouallaban@pm.me>

### CODE REVIEW

**Comment by piraka9011** [comment]
Windows build failing since there's a double repo pull somewhere:
```
colcon ERROR colcon build: Duplicate package names not supported:
- ros2bag:
    - d:\a\rosbag2\rosbag2\ros_ws\src\ros2\rosbag2\ros2bag
    - d:\a\rosbag2\rosbag2\ros_ws\src\rosbag2\ros2bag
```

**Comment by zmichaels11** [comment]
> Windows build failing since there's a double repo pull somewhere:
> 
> ```
> colcon ERROR colcon build: Duplicate package names not supported:
> - ros2bag:
>     - d:\a\rosbag2\rosbag2\ros_ws\src\ros2\rosbag2\ros2bag
>     - d:\a\rosbag2\rosbag2\ros_ws\src\rosbag2\ros2bag
> ```
> 
> It looks like this requires a custom `ros2.repos` file.

That looks like it pulled in `rosbag2` from the master `ros2.repos` file. Is this a bug in the `action-ros-ci`? I would think that it should filter out the current repo if it is found within the repos file.

**Comment by piraka9011** [comment]
Also the repos pull failed b/c the repo is not checked out with the `checkout` action.

**Comment by Karsten1987** [comment]
That'd be fantastic to have Windows github actions. We've recently switched over the ros2 ci to windows container builds. Maybe that's some point of interest to help debugging this problem?

**Comment by thomas-moulard** [comment]
https://github.com/ros-tooling/action-ros-ci/blob/master/src/action-ros-ci.ts#L145-L154 @piraka9011 PTAL

**Comment by piraka9011** [comment]
The first issue was resolved but then this issue popped up again :) ros-tooling/action-ros-ci#79
Will re-open once a resolution is found.

**Pull request closed without merging**
