### PR TITLE
use public recorder api in tests

### PR DESCRIPTION
**Pull request by Karsten1987**
sits on top of #740

### CODE REVIEW

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14412/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9185/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12085/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14509/)

**Review by emersonknapp — APPROVED** [review]
approved - but i might prefer to see that publication manager TODO done in this one - some of those tests are considerably longer now

**Comment by Karsten1987** [comment]
ok, I can do that. I'll have to re-iterate over this any way as there are segfaults on Linux and MSVC during the tests.

**Comment by Karsten1987** [comment]
I am always amazed by these one-character fixes (or differences between platforms). 

That CI is only to get the tests in order.
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14426/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9197/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12098/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14526/)

I am working now on a way to get the publisher manager in order without touching any other packages. Maybe I'll do an intermediate state first and reformat the remaining test fixtures all together in a second PR.

**Comment by emersonknapp** [comment]
> Maybe I'll do an intermediate state first 

Yes, it's ok if it's easier that way

**Comment by Karsten1987** [comment]
😩   I think the segfault is gone, but I have the feeling that our regex doesn't actually match the connext RMW identifier. I believe the new identifier is called `rmw_connextdds` without the `_cpp` suffix.

**Comment by Karsten1987** [comment]
let's see if the new regex does the job:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14427/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9198/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12099/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14527/)

**Comment by Karsten1987** [comment]
@emersonknapp please take a look once more. I'll table the tests for another PR as any modification to the publication manager has consequences for other packages as well. I'd much rather prefer to clean up all tests in multiple packages in a separate (set of ) PRs.

**Review by emersonknapp — APPROVED** [review]
Looks mostly like mechanical changes, seems good to me

**Comment by Karsten1987** [comment]
sanity check before merging:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14434/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9206/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12106/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14535/)

**Pull request merged**
