### PR TITLE
Update GenericSubscription's handle_message signature

### PR DESCRIPTION
**Pull request by emersonknapp**
Fixes the build since https://github.com/ros2/rclcpp/pull/1047

Signed-off-by: Emerson Knapp <emerson.b.knapp@gmail.com>

### CODE REVIEW

**Comment by emersonknapp** [comment]
Unblocks https://github.com/ros2/rosbag2/pull/372

**Comment by Karsten1987** [comment]
Just stumbled upon this myself here: https://github.com/ros2/rmw_iceoryx/pull/22/commits/52a4bb3091bd8138f60d98b84b76adb93f7e088e

Do you think we can actually shift this generic subscription to `rclcpp`? I feel like it deserves a more central place than rosbag to be reusable.

**Comment by emersonknapp** [comment]
Maybe generally valuable, we could port it over after the distro release.

**Comment by emersonknapp** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10140/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5709/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8243/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10035/)

**Comment by emersonknapp** [comment]
We're still trying to figure out why the test is failing in the Action CI... And that Linux failure on ROS CI is very confusing, some symbol thing in Connext.

Bit hard to keep on top of all the changes happening in the core

**Comment by Karsten1987** [comment]
do you have an idea why the GitHub Actions fails?
```
  26: [INFO] [1586831337.052728306] [rosbag2_transport]: Subscribed to topic '/string_topic'
  26: [ERROR] [1586831337.053618210] [rosbag2_transport]: Failed to record: Failed to create interrupt guard condition in Executor constructor: the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at /home/runner/work/rosbag2/rosbag2/ros_ws/src/ros2/rcl/rcl/src/rcl/guard_condition.c:69
  26: [       OK ] RecordIntegrationTestFixture.mixed_qos_subscribes (18 ms)
  26: [ RUN      ] RecordIntegrationTestFixture.duration_and_noncompatibility_policies_mixed
  26: [INFO] [1586831337.070318775] [rosbag2_transport]: Listening for topics...
  26: [INFO] [1586831337.072540884] [rosbag2_transport]: Subscribed to topic '/mixed_nondelivery_policies'
  26: [ERROR] [1586831337.073290787] [rosbag2_transport]: Failed to record: Failed to create interrupt guard condition in Executor constructor: the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at /home/runner/work/rosbag2/rosbag2/ros_ws/src/ros2/rcl/rcl/src/rcl/guard_condition.c:69
```?

**Comment by emersonknapp** [comment]
What you're pointing at there is actually an error message in shutdown after a successful test. It doesn't mark that test as failed. 

The failing test is timing out after 60 seconds - 

```
2020-04-14T02:30:03.1573398Z 27: [ RUN      ] RosBag2PlayQosOverrideTestFixture.topic_qos_profiles_overriden
2020-04-14T02:30:03.1573530Z 27: [INFO] [1586831337.995065607] [rosbag2_transport]: Overriding QoS profile for topic /test_topic
2020-04-14T02:30:03.1573807Z 27/34 Test #27: test_play__rmw_fastrtps_dynamic_cpp ......................***Timeout  60.06 sec
```

```
2020-04-14T02:30:03.1627329Z 
2020-04-14T02:30:03.1627422Z The following tests FAILED:
2020-04-14T02:30:03.1627704Z 	 18 - test_play__rmw_fastrtps_cpp (Timeout)
2020-04-14T02:30:03.1627958Z 	 27 - test_play__rmw_fastrtps_dynamic_cpp (Timeout)
```

**Comment by emersonknapp** [comment]
I'm looking at the test that is timing out and it doesn't look like it's doing what it says it does. I have to dig in further. Probably won't get to it until tomorrow morning, though.

**Comment by emersonknapp** [comment]
My guess is that the playback portion of the test is publishing all of its messages before our subscription connects to it, then waiting until the timeout for messages which do not arrive. It needs a rework to be timing-insensitive, I can do this first thing tomorrow.

**Comment by piraka9011** [comment]
* Linux [Build Status](https://ci.ros2.org/job/ci_linux/10162/)

**Comment by wjwwood** [comment]
CI lgtm, you can wait on the CI in https://github.com/ros2/rclcpp/pull/1047#issuecomment-613499118 or merge this now, either is fine I believe.

**Pull request merged**
