### PR TITLE
Add API samples for Python

### PR DESCRIPTION
**Pull request by gbiggs**
This PR adds API samples for the Python API. Three samples are added:

1. Writing data received from a topic in a node.
2. Writing synthetic data generated in a node.
3. Writing synthetic data generated without a node.

These samples accompany a [tutorial on writing data using the Python API](https://github.com/ros2/ros2_documentation/pull/2029).

This PR can be backported to Galactic.

### CODE REVIEW

**Review by MichaelOrlov — APPROVED** [review]
Looks good to me.

**Review by emersonknapp — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/2caa5eb5c736bf13186621013824cdbd/raw/2ecca7eef32ec2e5a26f9c80d0b619a6277d600c/ros2.repos
BUILD args:  --packages-above-and-dependencies bag_recorder_nodes_py
TEST args:  --packages-above bag_recorder_nodes_py
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10779
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17264/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11803/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17744/)

**Comment by MichaelOrlov** [comment]
@gbiggs Could you please rebase this PR to the latest rolling branch.  
It seems this PR branched from very outdated  version and CI fails due to changes in API.

**Comment by MichaelOrlov** [comment]
@gbiggs Honestly I more like folder names as it was proposed in #1068 i.e. `rosbag2_examples` instead `rosbag2_samples` 
"Samples" has a bit different associations in regards to the rosbag2. It's more associates with data samples rather than to the examples of API usage.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2022-9-15/27394/1

**Comment by DLu** [comment]
:+1: Let me know if I can help with this.

**Comment by MichaelOrlov** [comment]
@DLu It seems @gbiggs is busy with another tasks and roles.  
I think it would be reasonable to create a new PR with relative changes and proposals.
The help with it will be really appreciated.

**Comment by MichaelOrlov** [comment]
- Closing as done in #1253

**Pull request closed without merging**
