### PR TITLE
Foxy patch release 0.3.10

### PR DESCRIPTION
**Pull request by quarkytale**
Patch release 0.3.10

### CODE REVIEW

**Comment by clalancette** [comment]
From the CI, it looks like rosbag2_transport is crashing on some tests now with the following output:

```
-- run_test.py: extra environment variables:
 - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
-- run_test.py: invoking following command in '/tmp/ws/build_isolated/rosbag2_transport':
 - /tmp/ws/build_isolated/rosbag2_transport/test_record__rmw_fastrtps_cpp --gtest_output=xml:/tmp/ws/test_results/rosbag2_transport/test_record__rmw_fastrtps_cpp.gtest.xml
Running main() from gmock_main.cc
[==========] Running 7 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 7 tests from RecordIntegrationTestFixture
[ RUN      ] RecordIntegrationTestFixture.published_messages_from_multiple_topics_are_recorded
[INFO] [1678977012.500118532] [rosbag2_transport]: Listening for topics...
[INFO] [1678977012.501618750] [rosbag2_transport]: Subscribed to topic '/string_topic'
[INFO] [1678977012.602834916] [rosbag2_transport]: Subscribed to topic '/array_topic'
[INFO] [1678977012.602869609] [rosbag2_transport]: All requested topics are subscribed. Stopping discovery...
[       OK ] RecordIntegrationTestFixture.published_messages_from_multiple_topics_are_recorded (269 ms)
[ RUN      ] RecordIntegrationTestFixture.qos_is_stored_in_metadata
[INFO] [1678977012.764789424] [rosbag2_transport]: Listening for topics...
[INFO] [1678977012.765509735] [rosbag2_transport]: Subscribed to topic '/chatter'
[INFO] [1678977012.765677279] [rosbag2_transport]: All requested topics are subscribed. Stopping discovery...
[       OK ] RecordIntegrationTestFixture.qos_is_stored_in_metadata (160 ms)
[ RUN      ] RecordIntegrationTestFixture.records_sensor_data
[INFO] [1678977012.922963354] [rosbag2_transport]: Listening for topics...
[INFO] [1678977012.923697498] [rosbag2_transport]: Subscribed to topic '/string_topic'
[INFO] [1678977012.924003905] [rosbag2_transport]: All requested topics are subscribed. Stopping discovery...
-- run_test.py: return code -11
```

This needs to be investigated before we go forward with this.

**Comment by MichaelOrlov** [comment]
@clalancette Is it possible to get core dump from crash on CI?  
I don't have any idea on top of my head what caused segmentation fault during this test.  
Foxy branch has only one new commit from https://github.com/ros2/rosbag2/pull/1133 and I was running CI on it.  
CI was green.

**Comment by clalancette** [comment]
> @clalancette Is it possible to get core dump from crash on CI?

I don't know how to do that, unfortunately.

> I don't have any idea on top of my head what caused segmentation fault during this test.

Yeah, and I can't reproduce it locally either.  The tests pass just fine for me here.

**Comment by MichaelOrlov** [comment]
@ros-pull-request-builder retest this please

**Comment by clalancette** [comment]
Hm, very weird.  You got it to pass now.

@MichaelOrlov What do you think?  Should we go ahead with this?

**Comment by MichaelOrlov** [comment]
@clalancette Yes. I think we should go ahead with it.  
It seems some issue with underlying CI infrastructure.  
At least those [Check & create database dirs before writing bags #1133](https://github.com/ros2/rosbag2/pull/1133) PR was pretty much unrelated to the failed test.

**Comment by quarkytale** [comment]
@MichaelOrlov could you please approve if its good to go?

**Review by MichaelOrlov — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
@quarkytale Approved.

**Pull request merged**
