### PR TITLE
[Foxy] revert #1198 "rosbag2_storage_mcap: merge into rosbag2"

### PR DESCRIPTION
**Pull request by MichaelOrlov**
- Reverting #1198 due to Windows CI failures which were masked by another failure on CI.
- Relates #1198

This reverts commit e457d924d443e4aef47839f21ecb4495f2876871.

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/b5fe812945b757b423d4b3d855baaf8c/raw/ad6a580f2d4b0308a57ff7ba3d75df08791ed3ee/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_storage rosbag2_storage_default_plugins rosbag2_storage_mcap rosbag2_tests rosbag2_cpp ros2bag rosbag2_transport
TEST args:  --packages-above rosbag2_storage rosbag2_storage_default_plugins rosbag2_storage_mcap rosbag2_tests rosbag2_cpp ros2bag rosbag2_transport
ROS Distro: foxy
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12105
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18789/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13314/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19533/)

**Comment by MichaelOrlov** [comment]
Re-run with Focal
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12106
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18790/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13315/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19534/)

**Comment by MichaelOrlov** [comment]
Re-run CI with removed `rosbag2_storage_mcap` from the list of packages to build and test, since this package was completely removed.
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12107
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18791/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13316/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19535/)

**Review by emersonknapp — APPROVED** [review]

**Comment by emersonknapp** [comment]
Did those Windows warnings already exist on Foxy build before the original change?

**Comment by MichaelOrlov** [comment]
It will be addressed in https://github.com/ros2/rosbag2/pull/1349

**Comment by MichaelOrlov** [comment]
I have tested it on my local setup with Windows

**Comment by emersonknapp** [comment]
> It will be addressed in https://github.com/ros2/rosbag2/pull/1349

Not the test failure, there are MSBuild compiler warnings https://ci.ros2.org/job/ci_windows/19535/msbuild/

**Comment by MichaelOrlov** [comment]
> Not the test failure, there are MSBuild compiler warnings https://ci.ros2.org/job/ci_windows/19535/msbuild/

Yes, they were present before.
This type of warning `'YAML_CPP_DLL': macro redefinition` is a bit annoying and as far as recall we fixed them on rolling with multiple iterations https://github.com/ros2/rosbag2/pull/964 but not on Foxy.

**Comment by MichaelOrlov** [comment]
re-run CI after rebase
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18829/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13358/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19574/)

**Pull request merged**
