### PR TITLE
Backport. Fix for rosbag2::Player freeze when ctrl+c in pause mode

### PR DESCRIPTION
**Pull request by MichaelOrlov**
This is backprot of the #1002 to the Humble branch
Addressing bug report https://github.com/ros2/rosbag2/issues/1000

### CODE REVIEW

**Review by jhdcs — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
Running CI:
BUILD args: --packages-up-to rosbag2_transport rosbag2_tests
TEST args: --packages-select rosbag2_transport rosbag2_tests
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10298/
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16711/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11292/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17104/)

**Review by audrow — APPROVED** [review]

**Comment by MichaelOrlov** [comment]
It looks like some infrastructure related  errors on CI.
```
[1mII>[0m Attempting to switch all repositories to the 'morlov/humble-fix-for-player-freeze-after-ctrl+c-in-pause' branch[0m
(venv)[0m
[34m==>[0m [1m"/home/jenkins-agent/workspace/ci_linux/venv/bin/python" "/home/jenkins-agent/workspace/ci_linux/venv/bin/vcs" custom . --args checkout -b morlov/humble-fix-for-player-freeze-after-ctrl+c-in-pause --track origin/morlov/humble-fix-for-player-freeze-after-ctrl+c-in-pause[0m
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE.EE
[34m=== [1m./src/ament/ament_cmake[22m (git) ===[0m
[31mfatal: 'origin/morlov/humble-fix-for-player-freeze-after-ctrl+c-in-pause' is not a commit and a branch 'morlov/humble-fix-for-player-freeze-after-ctrl+c-in-pause' cannot be created from it[0m
[34m=== [1m./src/ament/ament_index[22m (git) ===[0m
[31mfatal: 'origin/morlov/humble-fix-for-player-freeze-after-ctrl+c-in-pause' is not a commit and a branch 'morlov/humble-fix-for-player-freeze-after-ctrl+c-in-pause' cannot be created from it[0m
```
And I have no idea what is wrong with it.
I did run similar CI configuration for master and it was working fine.

@audrow @clalancette Do you have any ideas what wrong with CI run?

**Comment by clalancette** [comment]
> @audrow @clalancette Do you have any ideas what wrong with CI run?

The problem is that this is a backport to humble, so you need to explicitly make a ros2.repos file targeting humble and use that (I know this is confusing, but switching the CI_ROS_DISTRO to `humble` doesn't do that).  That should fix the problem.

**Comment by MichaelOrlov** [comment]
@clalancette Thank you for the explanation.
Running CI one more time with repos file from Humble:
BUILD args: --packages-up-to rosbag2_transport rosbag2_tests
TEST args: --packages-select rosbag2_transport rosbag2_tests
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10313/
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16727/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11308/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17122/)

**Comment by clalancette** [comment]
> The following packages have unmet dependencies:
>  libssl-dev : Depends: libssl3 (= 3.0.2-0ubuntu1.1) but 3.0.2-0ubuntu1.2 is to be installed

This was an upstream Ubuntu issue that happened overnight.  We mostly aren't seeing them anymore, but you seem to be lucky and hit it again.  I reported it internally, but also I kicked off a new job (https://ci.ros2.org/job/ci_linux-aarch64/11309) which seems to be going fine.

**Comment by MichaelOrlov** [comment]
Result of new job https://ci.ros2.org/job/ci_linux-aarch64/11309
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11309/)

**Pull request merged**
