### PR TITLE
[Foxy backport] Validate QoS profile values are not negative. (#483)

### PR DESCRIPTION
**Pull request by dabonnie**
Backport of #483 

Signed-off-by: Jesse Ikawa <jikawa@amazon.com>

### CODE REVIEW

**Comment by dabonnie** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11775/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6852/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9613/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11718/)

**Comment by Karsten1987** [comment]
@clalancette let me know that for backport PRs, the `ros distro` dropdown menu within jenkins has to be set to `foxy` and not `rolling`, as the latter uses a newer version of pytest which requires a `pytest.ini` file.

**Comment by Karsten1987** [comment]
With ros distro target "foxy":
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11778/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6855/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9616/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11721/)

**Comment by Karsten1987** [comment]
Once more with a custom CI branch:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11780/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6857/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9618/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11723/)

**Comment by Karsten1987** [comment]
@j-rivero it looks like something went wrong in this PR here: https://github.com/ros2/ci/pull/471
The CI script used to make this backport PR pass CI is by revoking changes from the linked PR. @clalancette please correct me if I am wrong.

**Pull request merged**
