### PR TITLE
[foxy backport] Fix --topics flag for ros2 bag play being ignored for all bags after the first one (#619)

### PR DESCRIPTION
**Pull request by hexonxons**
Fix --topics flag for ros2 bag play being ignored for all bags after the first one. (#619)

### CODE REVIEW

**Comment by emersonknapp** [comment]
Gist: https://gist.githubusercontent.com/emersonknapp/33afd719aab5fd904e81c6cf1484d04a/raw/b88c19f0d6c83736d3056d5c7e0dac7bc1fdfd1e/ros2.repos
BUILD args: --packages-up-to rosbag2_cpp rosbag2_tests
TEST args: --packages-select rosbag2_cpp rosbag2_tests
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/7650
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13669/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8548/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11387/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13735/)

**Comment by emersonknapp** [comment]
This all looks good except for the Windows test (the CMake warnings are unrelated) - you'll probably notice all the rest of the tests have some `#ifdef _WIN32` workarounds - I'm surprised that it worked on the `master` CI actually. I'm also confused that the buildfarm build did not mark it green, given that `test_rosbag2_record_end_to_end` is marked `xfail`. @Karsten1987 do you understand why this would be marked yellow?

@hexonxons would you be able to add the same workaround logic for windows. Or, I think it would also be OK right now to just `ifdef` out the entire test on Windows. We have some backlog items to stabilize and re-enable these tests for Windows, and you shouldn't be blocked by that. We'll need to make sure the Windows CI build comes out green though before we merge.

**Comment by hexonxons** [comment]
@emersonknapp ofc, will try to put it under guard tomorrow.

Also, could you possibly tell me how long will it take to reach ubuntu repository after merging this?

**Comment by emersonknapp** [comment]
> Also, could you possibly tell me how long will it take to reach ubuntu repository after merging this?

We'd need to make a bloom release into foxy with an updated patch version - then it would happen in the next Foxy sync. Those syncs generally happen about once a month. I believe the last one was https://discourse.ros.org/t/preparing-for-foxy-sync-2020-01-07/18268 - so we're maybe overdue for another one. This process doesn't stick to a hard schedule, but we do get about 2-3 days warning in the form of such a discourse post so that we can make sure to get into the sync.

**Comment by emersonknapp** [comment]
I applied the guard, rebased to origin/foxy, and pushed to the branch (hope you don't mind), since I'm looking at this right now. If that makes the Windows build happy then I'll go ahead and merge, then follow up with a patch release.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13673/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8552/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11391/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13739/)

**Review by emersonknapp — APPROVED** [review]

**Pull request merged**
