### PR TITLE
Revert "[humble] Backport. Added support for filtering topics via regular expressions (#1034)-"

### PR DESCRIPTION
**Pull request by esteve**
Reverts ros2/rosbag2#1039

### CODE REVIEW

**Comment by esteve** [comment]
@MichaelOrlov this reverts the change in #1039 so that ABI compatibility is no longer broken in Humble

**Review by MichaelOrlov — APPROVED** [review]
@esteve Thanks a lot for reverting PR #1034.
I was almost about to do it by myself.

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/d7f365ef54aa3dfea351c0d9963a8e86/raw/cef7dd9c54b6813aa76eae37729e95019e64ffe2/ros2.repos
BUILD args:  --packages-above-and-dependencies ros2bag rosbag2_py rosbag2_storage rosbag2_storage_default_plugins rosbag2_transport rosbag2_tests
TEST args:  --packages-above ros2bag rosbag2_py rosbag2_storage rosbag2_storage_default_plugins rosbag2_transport rosbag2_tests
ROS Distro: humble
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10665
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17139/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11686/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17561/)

**Comment by MichaelOrlov** [comment]
Weird cmake error on Windows build. 
running Windows build one more time.
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17564/)

**Pull request merged**
