### PR TITLE
writer interface

### PR DESCRIPTION
**Pull request by Karsten1987**
currently based on #191 

@prajakta-gokhale fyi. This PR might also solve the issues encountered in your PR.
@piraka9011 You might want to adapt your "multifile reader" implementation against the API in this PR.

### CODE REVIEW

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8655/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4497/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7061/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8573/)

**Comment by Karsten1987** [comment]
addressing windows warnings:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8656/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4498/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7062/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8574/)

**Comment by Karsten1987** [comment]
@prajakta-gokhale I would prefer merging this PR which also contains #191 in order to go forward. It's basically applying the same pattern to both, the reader and the writer API. Let me know what you think.

**Comment by prajakta-gokhale** [comment]
LGTM. Thanks for pushing this forward!

**Pull request merged**
