### PR TITLE
[Compression - 1] Create new rosbag2 compression package

### PR DESCRIPTION
**Pull request by piraka9011**
Signed-off-by: Anas Abou Allaban <allabana@amazon.com>

### CODE REVIEW

**Comment by piraka9011** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8734/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4564/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7137/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8649/)

Gist: https://gist.githubusercontent.com/piraka9011/0d0b8831756163729555b9cc6828d399/raw/6c9a2a225972aee1ec7d1236bcd17f1b15322396/ros2.repos

**Comment by Karsten1987** [comment]
what's the difference here to #208 ?

**Comment by piraka9011** [comment]
@Karsten1987 Broke the original PR into multiple ones at the request of @thomas-moulard.

**Comment by thomas-moulard** [comment]
@Karsten1987 There are still a few things I'd like to see fixed in #208, we're going to merge what's ready step-by-step here.

**Pull request merged**
