### PR TITLE
cleanup cmakelists

### PR DESCRIPTION
**Pull request by Karsten1987**
There's no new functionality here. I solely cleaned up some copy-paste redundancies in the cmakelists.txt and ordered the tests alphabetically. 

sits on top of #725

### CODE REVIEW

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14313/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9102/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11999/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14418/)

**Comment by Karsten1987** [comment]
build failures to due missing API adaption in #725 

CI again:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14314/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9103/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12000/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14419/)

**Review by emersonknapp — APPROVED** [review]
Preemptively approving this - _assuming_ the entire change is contained in `CMakeLists.txt`. Pending the merge of #725, it seems

**Comment by Karsten1987** [comment]
I've rebased this branch to be on top of master directly without depending on #725. 

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14399/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9172/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12073/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14497/)

if CI turns out green, I'd take @emersonknapp approval to merge.

**Pull request merged**
