### PR TITLE
Bump mcap to v1.4.0

### PR DESCRIPTION
**Pull request by mosfet80**
- This PR updates mcap_vendor package to use latest mcap 1.4.0 version

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
minor version update and it does not change the dependencies. looks good to me.

**Review by james-rms — APPROVED** [review]

**Review by MichaelOrlov — APPROVED** [review]
LGTM with green CI

**Comment by MichaelOrlov** [comment]
Pulls: ros2/rosbag2#1774
Gist: https://gist.githubusercontent.com/MichaelOrlov/5236f1c28a2736b7829744ead1a5929d/raw/67d508ed96a8847c52a94d100028cd3821bd88ee/ros2.repos
BUILD args:  --packages-above-and-dependencies mcap_vendor rosbag2_storage_mcap rosbag2_transport rosbag2_cpp
TEST args:  --packages-above mcap_vendor rosbag2_storage_mcap rosbag2_transport rosbag2_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14392
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21646/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15933/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1151/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22364/)

**Comment by MichaelOrlov** [comment]
Re-run Linux and RHEL CI jobs after attempting to fix CI infrastructure failures.
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21653/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1157/)

**Comment by MichaelOrlov** [comment]
CI is green, merging then.

**Pull request merged**
