### PR TITLE
[foxy] Workaround for failing can_resolve_msg_with_idl_deps test on Windows

### PR DESCRIPTION
**Pull request by MichaelOrlov**
- Replaces https://github.com/ros2/rosidl/pull/745

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
Gist: https://gist.githubusercontent.com/MichaelOrlov/2e909519f827c1e52e4220c80d825748/raw/0383881f5585014742a4ae375487a19c387093b8/ros2.repos
BUILD args:  --packages-above-and-dependencies rosidl_adapter rosbag2_storage_mcap
TEST args:  --packages-above rosidl_adapter rosbag2_storage_mcap
ROS Distro: foxy
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12131
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18819/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13352/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19565/)

**Comment by MichaelOrlov** [comment]
Re-run CI for focal target
Gist: https://gist.githubusercontent.com/MichaelOrlov/2e909519f827c1e52e4220c80d825748/raw/0383881f5585014742a4ae375487a19c387093b8/ros2.repos
BUILD args:  --packages-above-and-dependencies rosidl_adapter rosbag2_storage_mcap
TEST args:  --packages-above rosidl_adapter rosbag2_storage_mcap
ROS Distro: foxy
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12132
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18820/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13353/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19566/)

**Comment by MichaelOrlov** [comment]
Re-run Widows CI job after fixing expectation in test
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19567/)

**Review by emersonknapp — APPROVED** [review]
LGTM

**Comment by MichaelOrlov** [comment]
Windows CI failed in an unrelated package 
```
Failed   <<< rviz_ogre_vendor [23min 39s, exited with code 1]
```
Re-running Windows CI job one more time.
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19569/)

**Comment by MichaelOrlov** [comment]
- Closing as will not be merged in favor of the https://github.com/ros2/rosbag2/pull/1347
- We decided to completely revert mcap bring up on foxy to avoid any issues and concerns in the future.

**Pull request closed without merging**
